//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGContextoAmbiente", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGContextoAmbiente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AmbienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuncaoEmExecucaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAuditoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutenticacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutenticacao_v2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutorizacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChaveContaArmazenamentoTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeContaArmazenamentoTenantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Ambiente {
            get {
                return this.AmbienteField;
            }
            set {
                if ((this.AmbienteField.Equals(value) != true)) {
                    this.AmbienteField = value;
                    this.RaisePropertyChanged("Ambiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoHost {
            get {
                return this.EnderecoHostField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoHostField, value) != true)) {
                    this.EnderecoHostField = value;
                    this.RaisePropertyChanged("EnderecoHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FuncaoEmExecucao {
            get {
                return this.FuncaoEmExecucaoField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncaoEmExecucaoField, value) != true)) {
                    this.FuncaoEmExecucaoField = value;
                    this.RaisePropertyChanged("FuncaoEmExecucao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdTenant {
            get {
                return this.IdTenantField;
            }
            set {
                if ((this.IdTenantField.Equals(value) != true)) {
                    this.IdTenantField = value;
                    this.RaisePropertyChanged("IdTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAuditoria {
            get {
                return this.IdentificadorDeAuditoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAuditoriaField, value) != true)) {
                    this.IdentificadorDeAuditoriaField = value;
                    this.RaisePropertyChanged("IdentificadorDeAuditoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutenticacao {
            get {
                return this.IdentificadorDeAutenticacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutenticacaoField, value) != true)) {
                    this.IdentificadorDeAutenticacaoField = value;
                    this.RaisePropertyChanged("IdentificadorDeAutenticacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutenticacao_v2 {
            get {
                return this.IdentificadorDeAutenticacao_v2Field;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutenticacao_v2Field, value) != true)) {
                    this.IdentificadorDeAutenticacao_v2Field = value;
                    this.RaisePropertyChanged("IdentificadorDeAutenticacao_v2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutorizacao {
            get {
                return this.IdentificadorDeAutorizacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutorizacaoField, value) != true)) {
                    this.IdentificadorDeAutorizacaoField = value;
                    this.RaisePropertyChanged("IdentificadorDeAutorizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeHost {
            get {
                return this.NomeHostField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeHostField, value) != true)) {
                    this.NomeHostField = value;
                    this.RaisePropertyChanged("NomeHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeTenant {
            get {
                return this.NomeTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeTenantField, value) != true)) {
                    this.NomeTenantField = value;
                    this.RaisePropertyChanged("NomeTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string ChaveContaArmazenamentoTenant {
            get {
                return this.ChaveContaArmazenamentoTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveContaArmazenamentoTenantField, value) != true)) {
                    this.ChaveContaArmazenamentoTenantField = value;
                    this.RaisePropertyChanged("ChaveContaArmazenamentoTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string GuidTenant {
            get {
                return this.GuidTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidTenantField, value) != true)) {
                    this.GuidTenantField = value;
                    this.RaisePropertyChanged("GuidTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string NomeContaArmazenamentoTenant {
            get {
                return this.NomeContaArmazenamentoTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeContaArmazenamentoTenantField, value) != true)) {
                    this.NomeContaArmazenamentoTenantField = value;
                    this.RaisePropertyChanged("NomeContaArmazenamentoTenant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGAutenticacao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGAutenticacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGTokenSessao TokenSessaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGTokenUsuario TokenUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGTokenSessao TokenSessao {
            get {
                return this.TokenSessaoField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenSessaoField, value) != true)) {
                    this.TokenSessaoField = value;
                    this.RaisePropertyChanged("TokenSessao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGTokenUsuario TokenUsuario {
            get {
                return this.TokenUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenUsuarioField, value) != true)) {
                    this.TokenUsuarioField = value;
                    this.RaisePropertyChanged("TokenUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGTokenSessao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGTokenSessao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdGerenciadorTokenField;
        
        private string IdSessaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdGerenciadorToken {
            get {
                return this.IdGerenciadorTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.IdGerenciadorTokenField, value) != true)) {
                    this.IdGerenciadorTokenField = value;
                    this.RaisePropertyChanged("IdGerenciadorToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdSessao {
            get {
                return this.IdSessaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSessaoField, value) != true)) {
                    this.IdSessaoField = value;
                    this.RaisePropertyChanged("IdSessao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGTokenUsuario", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGTokenUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SenhaField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidTenantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string GuidTenant {
            get {
                return this.GuidTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidTenantField, value) != true)) {
                    this.GuidTenantField = value;
                    this.RaisePropertyChanged("GuidTenant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CentroDeCusto", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class CentroDeCusto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoAlternativoField;
        
        private int CodigoDaEmpresaField;
        
        private string DescricaoField;
        
        private bool PermiteCadastrarFuncionarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAlternativo {
            get {
                return this.CodigoAlternativoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoAlternativoField, value) != true)) {
                    this.CodigoAlternativoField = value;
                    this.RaisePropertyChanged("CodigoAlternativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoDaEmpresa {
            get {
                return this.CodigoDaEmpresaField;
            }
            set {
                if ((this.CodigoDaEmpresaField.Equals(value) != true)) {
                    this.CodigoDaEmpresaField = value;
                    this.RaisePropertyChanged("CodigoDaEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool PermiteCadastrarFuncionario {
            get {
                return this.PermiteCadastrarFuncionarioField;
            }
            set {
                if ((this.PermiteCadastrarFuncionarioField.Equals(value) != true)) {
                    this.PermiteCadastrarFuncionarioField = value;
                    this.RaisePropertyChanged("PermiteCadastrarFuncionario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class ListaDeInconsistencias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.Inconsistencia[] InconsistenciasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.Inconsistencia[] Inconsistencias {
            get {
                return this.InconsistenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.InconsistenciasField, value) != true)) {
                    this.InconsistenciasField = value;
                    this.RaisePropertyChanged("Inconsistencias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class Inconsistencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AtributoRelacionadoField;
        
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtributoRelacionado {
            get {
                return this.AtributoRelacionadoField;
            }
            set {
                if ((object.ReferenceEquals(this.AtributoRelacionadoField, value) != true)) {
                    this.AtributoRelacionadoField = value;
                    this.RaisePropertyChanged("AtributoRelacionado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class FalhaInternaDeExecucao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorField, value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class FalhaDePermissao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CentroDeCusto_Exclusao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class CentroDeCusto_Exclusao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoField;
        
        private int CodigoDaEmpresaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoDaEmpresa {
            get {
                return this.CodigoDaEmpresaField;
            }
            set {
                if ((this.CodigoDaEmpresaField.Equals(value) != true)) {
                    this.CodigoDaEmpresaField = value;
                    this.RaisePropertyChanged("CodigoDaEmpresa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoCodigoEDescricaoGenericostring", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class RetornoCodigoEDescricaoGenericostring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoField;
        
        private string DescricaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="lg.com.br/svc", ConfigurationName="ServicoDeCentroDeCusto_20171.ServicoDeCentroDeCusto")]
    public interface ServicoDeCentroDeCusto {
        
        // CODEGEN: Generating message contract since message CadastreCentroDeCustoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeCentroDeCusto/CadastreCentroDeCusto", ReplyAction="lg.com.br/svc/ServicoDeCentroDeCusto/CadastreCentroDeCustoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeCentroDeCusto/CadastreCentroDeCustoListaDeInconsistenciasF" +
            "ault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeCentroDeCusto/CadastreCentroDeCustoInconsistenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeCentroDeCusto/CadastreCentroDeCustoFalhaInternaDeExecucaoF" +
            "ault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeCentroDeCusto/CadastreCentroDeCustoFalhaDePermissaoFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.CadastreCentroDeCustoResponse CadastreCentroDeCusto(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.CadastreCentroDeCustoRequest request);
        
        // CODEGEN: Generating message contract since message AtualizeCentroDeCustoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeCentroDeCusto/AtualizeCentroDeCusto", ReplyAction="lg.com.br/svc/ServicoDeCentroDeCusto/AtualizeCentroDeCustoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeCentroDeCusto/AtualizeCentroDeCustoListaDeInconsistenciasF" +
            "ault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeCentroDeCusto/AtualizeCentroDeCustoInconsistenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeCentroDeCusto/AtualizeCentroDeCustoFalhaInternaDeExecucaoF" +
            "ault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeCentroDeCusto/AtualizeCentroDeCustoFalhaDePermissaoFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.AtualizeCentroDeCustoResponse AtualizeCentroDeCusto(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.AtualizeCentroDeCustoRequest request);
        
        // CODEGEN: Generating message contract since message ExcluaCentroDeCustoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeCentroDeCusto/ExcluaCentroDeCusto", ReplyAction="lg.com.br/svc/ServicoDeCentroDeCusto/ExcluaCentroDeCustoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeCentroDeCusto/ExcluaCentroDeCustoListaDeInconsistenciasFau" +
            "lt", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeCentroDeCusto/ExcluaCentroDeCustoInconsistenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeCentroDeCusto/ExcluaCentroDeCustoFalhaInternaDeExecucaoFau" +
            "lt", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeCentroDeCusto/ExcluaCentroDeCustoFalhaDePermissaoFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ExcluaCentroDeCustoResponse ExcluaCentroDeCusto(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ExcluaCentroDeCustoRequest request);
        
        // CODEGEN: Generating message contract since message ConsulteCentrosDeCustosRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeCentroDeCusto/ConsulteCentrosDeCustos", ReplyAction="lg.com.br/svc/ServicoDeCentroDeCusto/ConsulteCentrosDeCustosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeCentroDeCusto/ConsulteCentrosDeCustosListaDeInconsistencia" +
            "sFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeCentroDeCusto/ConsulteCentrosDeCustosInconsistenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeCentroDeCusto/ConsulteCentrosDeCustosFalhaInternaDeExecuca" +
            "oFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeCentroDeCusto/ConsulteCentrosDeCustosFalhaDePermissaoFault" +
            "", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ConsulteCentrosDeCustosResponse ConsulteCentrosDeCustos(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ConsulteCentrosDeCustosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CadastreCentroDeCusto", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class CadastreCentroDeCustoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.CentroDeCusto centroDeCusto;
        
        public CadastreCentroDeCustoRequest() {
        }
        
        public CadastreCentroDeCustoRequest(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.CentroDeCusto centroDeCusto) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.centroDeCusto = centroDeCusto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CadastreCentroDeCustoResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class CadastreCentroDeCustoResponse {
        
        public CadastreCentroDeCustoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AtualizeCentroDeCusto", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class AtualizeCentroDeCustoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.CentroDeCusto centroDeCusto;
        
        public AtualizeCentroDeCustoRequest() {
        }
        
        public AtualizeCentroDeCustoRequest(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.CentroDeCusto centroDeCusto) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.centroDeCusto = centroDeCusto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AtualizeCentroDeCustoResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class AtualizeCentroDeCustoResponse {
        
        public AtualizeCentroDeCustoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExcluaCentroDeCusto", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ExcluaCentroDeCustoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.CentroDeCusto_Exclusao centroDeCusto_Exclusao;
        
        public ExcluaCentroDeCustoRequest() {
        }
        
        public ExcluaCentroDeCustoRequest(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.CentroDeCusto_Exclusao centroDeCusto_Exclusao) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.centroDeCusto_Exclusao = centroDeCusto_Exclusao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExcluaCentroDeCustoResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ExcluaCentroDeCustoResponse {
        
        public ExcluaCentroDeCustoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsulteCentrosDeCustos", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ConsulteCentrosDeCustosRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public int CodigoEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=1)]
        public string CodigoCentroDeCusto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=2)]
        public string DescricaoCentroDeCusto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=3)]
        public string CodigoDoGrupoHierarquico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=4)]
        public double CodigoDaLotacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=5)]
        public bool SomenteComPermissaoParaCadastrarFuncionarios;
        
        public ConsulteCentrosDeCustosRequest() {
        }
        
        public ConsulteCentrosDeCustosRequest(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresa, string CodigoCentroDeCusto, string DescricaoCentroDeCusto, string CodigoDoGrupoHierarquico, double CodigoDaLotacao, bool SomenteComPermissaoParaCadastrarFuncionarios) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.CodigoEmpresa = CodigoEmpresa;
            this.CodigoCentroDeCusto = CodigoCentroDeCusto;
            this.DescricaoCentroDeCusto = DescricaoCentroDeCusto;
            this.CodigoDoGrupoHierarquico = CodigoDoGrupoHierarquico;
            this.CodigoDaLotacao = CodigoDaLotacao;
            this.SomenteComPermissaoParaCadastrarFuncionarios = SomenteComPermissaoParaCadastrarFuncionarios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsulteCentrosDeCustosResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ConsulteCentrosDeCustosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.RetornoCodigoEDescricaoGenericostring[] ConsulteCentrosDeCustosResult;
        
        public ConsulteCentrosDeCustosResponse() {
        }
        
        public ConsulteCentrosDeCustosResponse(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.RetornoCodigoEDescricaoGenericostring[] ConsulteCentrosDeCustosResult) {
            this.ConsulteCentrosDeCustosResult = ConsulteCentrosDeCustosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoDeCentroDeCustoChannel : WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ServicoDeCentroDeCusto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoDeCentroDeCustoClient : System.ServiceModel.ClientBase<WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ServicoDeCentroDeCusto>, WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ServicoDeCentroDeCusto {
        
        public ServicoDeCentroDeCustoClient() {
        }
        
        public ServicoDeCentroDeCustoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoDeCentroDeCustoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoDeCentroDeCustoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoDeCentroDeCustoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.CadastreCentroDeCustoResponse WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ServicoDeCentroDeCusto.CadastreCentroDeCusto(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.CadastreCentroDeCustoRequest request) {
            return base.Channel.CadastreCentroDeCusto(request);
        }
        
        public void CadastreCentroDeCusto(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.CentroDeCusto centroDeCusto) {
            WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.CadastreCentroDeCustoRequest inValue = new WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.CadastreCentroDeCustoRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.centroDeCusto = centroDeCusto;
            WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.CadastreCentroDeCustoResponse retVal = ((WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ServicoDeCentroDeCusto)(this)).CadastreCentroDeCusto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.AtualizeCentroDeCustoResponse WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ServicoDeCentroDeCusto.AtualizeCentroDeCusto(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.AtualizeCentroDeCustoRequest request) {
            return base.Channel.AtualizeCentroDeCusto(request);
        }
        
        public void AtualizeCentroDeCusto(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.CentroDeCusto centroDeCusto) {
            WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.AtualizeCentroDeCustoRequest inValue = new WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.AtualizeCentroDeCustoRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.centroDeCusto = centroDeCusto;
            WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.AtualizeCentroDeCustoResponse retVal = ((WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ServicoDeCentroDeCusto)(this)).AtualizeCentroDeCusto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ExcluaCentroDeCustoResponse WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ServicoDeCentroDeCusto.ExcluaCentroDeCusto(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ExcluaCentroDeCustoRequest request) {
            return base.Channel.ExcluaCentroDeCusto(request);
        }
        
        public void ExcluaCentroDeCusto(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.CentroDeCusto_Exclusao centroDeCusto_Exclusao) {
            WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ExcluaCentroDeCustoRequest inValue = new WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ExcluaCentroDeCustoRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.centroDeCusto_Exclusao = centroDeCusto_Exclusao;
            WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ExcluaCentroDeCustoResponse retVal = ((WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ServicoDeCentroDeCusto)(this)).ExcluaCentroDeCusto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ConsulteCentrosDeCustosResponse WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ServicoDeCentroDeCusto.ConsulteCentrosDeCustos(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ConsulteCentrosDeCustosRequest request) {
            return base.Channel.ConsulteCentrosDeCustos(request);
        }
        
        public WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.RetornoCodigoEDescricaoGenericostring[] ConsulteCentrosDeCustos(WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresa, string CodigoCentroDeCusto, string DescricaoCentroDeCusto, string CodigoDoGrupoHierarquico, double CodigoDaLotacao, bool SomenteComPermissaoParaCadastrarFuncionarios) {
            WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ConsulteCentrosDeCustosRequest inValue = new WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ConsulteCentrosDeCustosRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.CodigoEmpresa = CodigoEmpresa;
            inValue.CodigoCentroDeCusto = CodigoCentroDeCusto;
            inValue.DescricaoCentroDeCusto = DescricaoCentroDeCusto;
            inValue.CodigoDoGrupoHierarquico = CodigoDoGrupoHierarquico;
            inValue.CodigoDaLotacao = CodigoDaLotacao;
            inValue.SomenteComPermissaoParaCadastrarFuncionarios = SomenteComPermissaoParaCadastrarFuncionarios;
            WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ConsulteCentrosDeCustosResponse retVal = ((WCFTestClient.Dominio.ServicoDeCentroDeCusto_20171.ServicoDeCentroDeCusto)(this)).ConsulteCentrosDeCustos(inValue);
            return retVal.ConsulteCentrosDeCustosResult;
        }
    }
}
