//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGContextoAmbiente", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGContextoAmbiente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AmbienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuncaoEmExecucaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAuditoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutenticacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutenticacao_v2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutorizacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChaveContaArmazenamentoTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeContaArmazenamentoTenantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Ambiente {
            get {
                return this.AmbienteField;
            }
            set {
                if ((this.AmbienteField.Equals(value) != true)) {
                    this.AmbienteField = value;
                    this.RaisePropertyChanged("Ambiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoHost {
            get {
                return this.EnderecoHostField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoHostField, value) != true)) {
                    this.EnderecoHostField = value;
                    this.RaisePropertyChanged("EnderecoHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FuncaoEmExecucao {
            get {
                return this.FuncaoEmExecucaoField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncaoEmExecucaoField, value) != true)) {
                    this.FuncaoEmExecucaoField = value;
                    this.RaisePropertyChanged("FuncaoEmExecucao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdTenant {
            get {
                return this.IdTenantField;
            }
            set {
                if ((this.IdTenantField.Equals(value) != true)) {
                    this.IdTenantField = value;
                    this.RaisePropertyChanged("IdTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAuditoria {
            get {
                return this.IdentificadorDeAuditoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAuditoriaField, value) != true)) {
                    this.IdentificadorDeAuditoriaField = value;
                    this.RaisePropertyChanged("IdentificadorDeAuditoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutenticacao {
            get {
                return this.IdentificadorDeAutenticacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutenticacaoField, value) != true)) {
                    this.IdentificadorDeAutenticacaoField = value;
                    this.RaisePropertyChanged("IdentificadorDeAutenticacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutenticacao_v2 {
            get {
                return this.IdentificadorDeAutenticacao_v2Field;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutenticacao_v2Field, value) != true)) {
                    this.IdentificadorDeAutenticacao_v2Field = value;
                    this.RaisePropertyChanged("IdentificadorDeAutenticacao_v2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutorizacao {
            get {
                return this.IdentificadorDeAutorizacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutorizacaoField, value) != true)) {
                    this.IdentificadorDeAutorizacaoField = value;
                    this.RaisePropertyChanged("IdentificadorDeAutorizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeHost {
            get {
                return this.NomeHostField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeHostField, value) != true)) {
                    this.NomeHostField = value;
                    this.RaisePropertyChanged("NomeHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeTenant {
            get {
                return this.NomeTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeTenantField, value) != true)) {
                    this.NomeTenantField = value;
                    this.RaisePropertyChanged("NomeTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string ChaveContaArmazenamentoTenant {
            get {
                return this.ChaveContaArmazenamentoTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveContaArmazenamentoTenantField, value) != true)) {
                    this.ChaveContaArmazenamentoTenantField = value;
                    this.RaisePropertyChanged("ChaveContaArmazenamentoTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string GuidTenant {
            get {
                return this.GuidTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidTenantField, value) != true)) {
                    this.GuidTenantField = value;
                    this.RaisePropertyChanged("GuidTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string NomeContaArmazenamentoTenant {
            get {
                return this.NomeContaArmazenamentoTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeContaArmazenamentoTenantField, value) != true)) {
                    this.NomeContaArmazenamentoTenantField = value;
                    this.RaisePropertyChanged("NomeContaArmazenamentoTenant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGAutenticacao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGAutenticacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGTokenSessao TokenSessaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGTokenUsuario TokenUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGTokenSessao TokenSessao {
            get {
                return this.TokenSessaoField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenSessaoField, value) != true)) {
                    this.TokenSessaoField = value;
                    this.RaisePropertyChanged("TokenSessao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGTokenUsuario TokenUsuario {
            get {
                return this.TokenUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenUsuarioField, value) != true)) {
                    this.TokenUsuarioField = value;
                    this.RaisePropertyChanged("TokenUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGTokenSessao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGTokenSessao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdGerenciadorTokenField;
        
        private string IdSessaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdGerenciadorToken {
            get {
                return this.IdGerenciadorTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.IdGerenciadorTokenField, value) != true)) {
                    this.IdGerenciadorTokenField = value;
                    this.RaisePropertyChanged("IdGerenciadorToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdSessao {
            get {
                return this.IdSessaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSessaoField, value) != true)) {
                    this.IdSessaoField = value;
                    this.RaisePropertyChanged("IdSessao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGTokenUsuario", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGTokenUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SenhaField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidTenantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string GuidTenant {
            get {
                return this.GuidTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidTenantField, value) != true)) {
                    this.GuidTenantField = value;
                    this.RaisePropertyChanged("GuidTenant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NaturezaProfissional", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class NaturezaProfissional : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoDaEmpresaField;
        
        private int CodigoItemField;
        
        private string DescricaoItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoDaEmpresa {
            get {
                return this.CodigoDaEmpresaField;
            }
            set {
                if ((this.CodigoDaEmpresaField.Equals(value) != true)) {
                    this.CodigoDaEmpresaField = value;
                    this.RaisePropertyChanged("CodigoDaEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoItem {
            get {
                return this.CodigoItemField;
            }
            set {
                if ((this.CodigoItemField.Equals(value) != true)) {
                    this.CodigoItemField = value;
                    this.RaisePropertyChanged("CodigoItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DescricaoItem {
            get {
                return this.DescricaoItemField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoItemField, value) != true)) {
                    this.DescricaoItemField = value;
                    this.RaisePropertyChanged("DescricaoItem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class Inconsistencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AtributoRelacionadoField;
        
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtributoRelacionado {
            get {
                return this.AtributoRelacionadoField;
            }
            set {
                if ((object.ReferenceEquals(this.AtributoRelacionadoField, value) != true)) {
                    this.AtributoRelacionadoField = value;
                    this.RaisePropertyChanged("AtributoRelacionado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class ListaDeInconsistencias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.Inconsistencia[] InconsistenciasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.Inconsistencia[] Inconsistencias {
            get {
                return this.InconsistenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.InconsistenciasField, value) != true)) {
                    this.InconsistenciasField = value;
                    this.RaisePropertyChanged("Inconsistencias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class FalhaInternaDeExecucao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorField, value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class FalhaDePermissao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NaturezaProfissional_Exclusao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class NaturezaProfissional_Exclusao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoDaEmpresaField;
        
        private int CodigoItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoDaEmpresa {
            get {
                return this.CodigoDaEmpresaField;
            }
            set {
                if ((this.CodigoDaEmpresaField.Equals(value) != true)) {
                    this.CodigoDaEmpresaField = value;
                    this.RaisePropertyChanged("CodigoDaEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoItem {
            get {
                return this.CodigoItemField;
            }
            set {
                if ((this.CodigoItemField.Equals(value) != true)) {
                    this.CodigoItemField = value;
                    this.RaisePropertyChanged("CodigoItem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="lg.com.br/svc", ConfigurationName="ServicoDeTabelaAuxiliar_20171.ServicoDeTabelaAuxiliar")]
    public interface ServicoDeTabelaAuxiliar {
        
        // CODEGEN: Generating message contract since message CadastreNaturezaProfissionalRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/CadastreNaturezaProfissional", ReplyAction="lg.com.br/svc/ServicoDeTabelaAuxiliar/CadastreNaturezaProfissionalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/CadastreNaturezaProfissionalInconsistenciaF" +
            "ault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/CadastreNaturezaProfissionalListaDeInconsis" +
            "tenciasFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/CadastreNaturezaProfissionalFalhaInternaDeE" +
            "xecucaoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/CadastreNaturezaProfissionalFalhaDePermissa" +
            "oFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.CadastreNaturezaProfissionalResponse CadastreNaturezaProfissional(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.CadastreNaturezaProfissionalRequest request);
        
        // CODEGEN: Generating message contract since message AtualizeNaturezaProfissionalRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/AtualizeNaturezaProfissional", ReplyAction="lg.com.br/svc/ServicoDeTabelaAuxiliar/AtualizeNaturezaProfissionalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/AtualizeNaturezaProfissionalInconsistenciaF" +
            "ault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/AtualizeNaturezaProfissionalListaDeInconsis" +
            "tenciasFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/AtualizeNaturezaProfissionalFalhaInternaDeE" +
            "xecucaoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/AtualizeNaturezaProfissionalFalhaDePermissa" +
            "oFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.AtualizeNaturezaProfissionalResponse AtualizeNaturezaProfissional(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.AtualizeNaturezaProfissionalRequest request);
        
        // CODEGEN: Generating message contract since message ExcluaNaturezaProfissionalRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/ExcluaNaturezaProfissional", ReplyAction="lg.com.br/svc/ServicoDeTabelaAuxiliar/ExcluaNaturezaProfissionalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/ExcluaNaturezaProfissionalListaDeInconsiste" +
            "nciasFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/ExcluaNaturezaProfissionalInconsistenciaFau" +
            "lt", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/ExcluaNaturezaProfissionalFalhaInternaDeExe" +
            "cucaoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/ExcluaNaturezaProfissionalFalhaDePermissaoF" +
            "ault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ExcluaNaturezaProfissionalResponse ExcluaNaturezaProfissional(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ExcluaNaturezaProfissionalRequest request);
        
        // CODEGEN: Generating message contract since message ExisteNaturezaProfissionalRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/ExisteNaturezaProfissional", ReplyAction="lg.com.br/svc/ServicoDeTabelaAuxiliar/ExisteNaturezaProfissionalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/ExisteNaturezaProfissionalInconsistenciaFau" +
            "lt", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/ExisteNaturezaProfissionalListaDeInconsiste" +
            "nciasFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/ExisteNaturezaProfissionalFalhaInternaDeExe" +
            "cucaoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeTabelaAuxiliar/ExisteNaturezaProfissionalFalhaDePermissaoF" +
            "ault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ExisteNaturezaProfissionalResponse ExisteNaturezaProfissional(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ExisteNaturezaProfissionalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CadastreNaturezaProfissional", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class CadastreNaturezaProfissionalRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public int CodigoEmpresaParaAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=1)]
        public WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.NaturezaProfissional NaturezaProfissional;
        
        public CadastreNaturezaProfissionalRequest() {
        }
        
        public CadastreNaturezaProfissionalRequest(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaParaAutenticacao, WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.NaturezaProfissional NaturezaProfissional) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.CodigoEmpresaParaAutenticacao = CodigoEmpresaParaAutenticacao;
            this.NaturezaProfissional = NaturezaProfissional;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CadastreNaturezaProfissionalResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class CadastreNaturezaProfissionalResponse {
        
        public CadastreNaturezaProfissionalResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AtualizeNaturezaProfissional", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class AtualizeNaturezaProfissionalRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public int CodigoEmpresaParaAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=1)]
        public WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.NaturezaProfissional NaturezaProfissional;
        
        public AtualizeNaturezaProfissionalRequest() {
        }
        
        public AtualizeNaturezaProfissionalRequest(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaParaAutenticacao, WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.NaturezaProfissional NaturezaProfissional) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.CodigoEmpresaParaAutenticacao = CodigoEmpresaParaAutenticacao;
            this.NaturezaProfissional = NaturezaProfissional;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AtualizeNaturezaProfissionalResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class AtualizeNaturezaProfissionalResponse {
        
        public AtualizeNaturezaProfissionalResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExcluaNaturezaProfissional", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ExcluaNaturezaProfissionalRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public int CodigoEmpresaParaAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=1)]
        public WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.NaturezaProfissional_Exclusao NaturezaProfissional;
        
        public ExcluaNaturezaProfissionalRequest() {
        }
        
        public ExcluaNaturezaProfissionalRequest(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaParaAutenticacao, WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.NaturezaProfissional_Exclusao NaturezaProfissional) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.CodigoEmpresaParaAutenticacao = CodigoEmpresaParaAutenticacao;
            this.NaturezaProfissional = NaturezaProfissional;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExcluaNaturezaProfissionalResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ExcluaNaturezaProfissionalResponse {
        
        public ExcluaNaturezaProfissionalResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExisteNaturezaProfissional", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ExisteNaturezaProfissionalRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public int CodigoEmpresaParaAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=1)]
        public WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.NaturezaProfissional NaturezaProfissional;
        
        public ExisteNaturezaProfissionalRequest() {
        }
        
        public ExisteNaturezaProfissionalRequest(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaParaAutenticacao, WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.NaturezaProfissional NaturezaProfissional) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.CodigoEmpresaParaAutenticacao = CodigoEmpresaParaAutenticacao;
            this.NaturezaProfissional = NaturezaProfissional;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExisteNaturezaProfissionalResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ExisteNaturezaProfissionalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public bool ExisteNaturezaProfissionalResult;
        
        public ExisteNaturezaProfissionalResponse() {
        }
        
        public ExisteNaturezaProfissionalResponse(bool ExisteNaturezaProfissionalResult) {
            this.ExisteNaturezaProfissionalResult = ExisteNaturezaProfissionalResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoDeTabelaAuxiliarChannel : WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ServicoDeTabelaAuxiliar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoDeTabelaAuxiliarClient : System.ServiceModel.ClientBase<WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ServicoDeTabelaAuxiliar>, WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ServicoDeTabelaAuxiliar {
        
        public ServicoDeTabelaAuxiliarClient() {
        }
        
        public ServicoDeTabelaAuxiliarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoDeTabelaAuxiliarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoDeTabelaAuxiliarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoDeTabelaAuxiliarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.CadastreNaturezaProfissionalResponse WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ServicoDeTabelaAuxiliar.CadastreNaturezaProfissional(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.CadastreNaturezaProfissionalRequest request) {
            return base.Channel.CadastreNaturezaProfissional(request);
        }
        
        public void CadastreNaturezaProfissional(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaParaAutenticacao, WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.NaturezaProfissional NaturezaProfissional) {
            WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.CadastreNaturezaProfissionalRequest inValue = new WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.CadastreNaturezaProfissionalRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.CodigoEmpresaParaAutenticacao = CodigoEmpresaParaAutenticacao;
            inValue.NaturezaProfissional = NaturezaProfissional;
            WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.CadastreNaturezaProfissionalResponse retVal = ((WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ServicoDeTabelaAuxiliar)(this)).CadastreNaturezaProfissional(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.AtualizeNaturezaProfissionalResponse WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ServicoDeTabelaAuxiliar.AtualizeNaturezaProfissional(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.AtualizeNaturezaProfissionalRequest request) {
            return base.Channel.AtualizeNaturezaProfissional(request);
        }
        
        public void AtualizeNaturezaProfissional(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaParaAutenticacao, WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.NaturezaProfissional NaturezaProfissional) {
            WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.AtualizeNaturezaProfissionalRequest inValue = new WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.AtualizeNaturezaProfissionalRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.CodigoEmpresaParaAutenticacao = CodigoEmpresaParaAutenticacao;
            inValue.NaturezaProfissional = NaturezaProfissional;
            WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.AtualizeNaturezaProfissionalResponse retVal = ((WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ServicoDeTabelaAuxiliar)(this)).AtualizeNaturezaProfissional(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ExcluaNaturezaProfissionalResponse WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ServicoDeTabelaAuxiliar.ExcluaNaturezaProfissional(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ExcluaNaturezaProfissionalRequest request) {
            return base.Channel.ExcluaNaturezaProfissional(request);
        }
        
        public void ExcluaNaturezaProfissional(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaParaAutenticacao, WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.NaturezaProfissional_Exclusao NaturezaProfissional) {
            WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ExcluaNaturezaProfissionalRequest inValue = new WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ExcluaNaturezaProfissionalRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.CodigoEmpresaParaAutenticacao = CodigoEmpresaParaAutenticacao;
            inValue.NaturezaProfissional = NaturezaProfissional;
            WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ExcluaNaturezaProfissionalResponse retVal = ((WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ServicoDeTabelaAuxiliar)(this)).ExcluaNaturezaProfissional(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ExisteNaturezaProfissionalResponse WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ServicoDeTabelaAuxiliar.ExisteNaturezaProfissional(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ExisteNaturezaProfissionalRequest request) {
            return base.Channel.ExisteNaturezaProfissional(request);
        }
        
        public bool ExisteNaturezaProfissional(WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaParaAutenticacao, WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.NaturezaProfissional NaturezaProfissional) {
            WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ExisteNaturezaProfissionalRequest inValue = new WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ExisteNaturezaProfissionalRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.CodigoEmpresaParaAutenticacao = CodigoEmpresaParaAutenticacao;
            inValue.NaturezaProfissional = NaturezaProfissional;
            WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ExisteNaturezaProfissionalResponse retVal = ((WCFTestClient.Dominio.ServicoDeTabelaAuxiliar_20171.ServicoDeTabelaAuxiliar)(this)).ExisteNaturezaProfissional(inValue);
            return retVal.ExisteNaturezaProfissionalResult;
        }
    }
}
