//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGContextoAmbiente", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGContextoAmbiente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AmbienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuncaoEmExecucaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAuditoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutenticacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutenticacao_v2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutorizacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChaveContaArmazenamentoTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeContaArmazenamentoTenantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Ambiente {
            get {
                return this.AmbienteField;
            }
            set {
                if ((this.AmbienteField.Equals(value) != true)) {
                    this.AmbienteField = value;
                    this.RaisePropertyChanged("Ambiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoHost {
            get {
                return this.EnderecoHostField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoHostField, value) != true)) {
                    this.EnderecoHostField = value;
                    this.RaisePropertyChanged("EnderecoHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FuncaoEmExecucao {
            get {
                return this.FuncaoEmExecucaoField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncaoEmExecucaoField, value) != true)) {
                    this.FuncaoEmExecucaoField = value;
                    this.RaisePropertyChanged("FuncaoEmExecucao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdTenant {
            get {
                return this.IdTenantField;
            }
            set {
                if ((this.IdTenantField.Equals(value) != true)) {
                    this.IdTenantField = value;
                    this.RaisePropertyChanged("IdTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAuditoria {
            get {
                return this.IdentificadorDeAuditoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAuditoriaField, value) != true)) {
                    this.IdentificadorDeAuditoriaField = value;
                    this.RaisePropertyChanged("IdentificadorDeAuditoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutenticacao {
            get {
                return this.IdentificadorDeAutenticacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutenticacaoField, value) != true)) {
                    this.IdentificadorDeAutenticacaoField = value;
                    this.RaisePropertyChanged("IdentificadorDeAutenticacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutenticacao_v2 {
            get {
                return this.IdentificadorDeAutenticacao_v2Field;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutenticacao_v2Field, value) != true)) {
                    this.IdentificadorDeAutenticacao_v2Field = value;
                    this.RaisePropertyChanged("IdentificadorDeAutenticacao_v2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutorizacao {
            get {
                return this.IdentificadorDeAutorizacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutorizacaoField, value) != true)) {
                    this.IdentificadorDeAutorizacaoField = value;
                    this.RaisePropertyChanged("IdentificadorDeAutorizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeHost {
            get {
                return this.NomeHostField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeHostField, value) != true)) {
                    this.NomeHostField = value;
                    this.RaisePropertyChanged("NomeHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeTenant {
            get {
                return this.NomeTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeTenantField, value) != true)) {
                    this.NomeTenantField = value;
                    this.RaisePropertyChanged("NomeTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string ChaveContaArmazenamentoTenant {
            get {
                return this.ChaveContaArmazenamentoTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveContaArmazenamentoTenantField, value) != true)) {
                    this.ChaveContaArmazenamentoTenantField = value;
                    this.RaisePropertyChanged("ChaveContaArmazenamentoTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string GuidTenant {
            get {
                return this.GuidTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidTenantField, value) != true)) {
                    this.GuidTenantField = value;
                    this.RaisePropertyChanged("GuidTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string NomeContaArmazenamentoTenant {
            get {
                return this.NomeContaArmazenamentoTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeContaArmazenamentoTenantField, value) != true)) {
                    this.NomeContaArmazenamentoTenantField = value;
                    this.RaisePropertyChanged("NomeContaArmazenamentoTenant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGAutenticacao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGAutenticacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGTokenSessao TokenSessaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGTokenUsuario TokenUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGTokenSessao TokenSessao {
            get {
                return this.TokenSessaoField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenSessaoField, value) != true)) {
                    this.TokenSessaoField = value;
                    this.RaisePropertyChanged("TokenSessao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGTokenUsuario TokenUsuario {
            get {
                return this.TokenUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenUsuarioField, value) != true)) {
                    this.TokenUsuarioField = value;
                    this.RaisePropertyChanged("TokenUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGTokenSessao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGTokenSessao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdGerenciadorTokenField;
        
        private string IdSessaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdGerenciadorToken {
            get {
                return this.IdGerenciadorTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.IdGerenciadorTokenField, value) != true)) {
                    this.IdGerenciadorTokenField = value;
                    this.RaisePropertyChanged("IdGerenciadorToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdSessao {
            get {
                return this.IdSessaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSessaoField, value) != true)) {
                    this.IdSessaoField = value;
                    this.RaisePropertyChanged("IdSessao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGTokenUsuario", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGTokenUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SenhaField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidTenantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string GuidTenant {
            get {
                return this.GuidTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidTenantField, value) != true)) {
                    this.GuidTenantField = value;
                    this.RaisePropertyChanged("GuidTenant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemAtributoAdicionalTipoTabela", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class ItemAtributoAdicionalTipoTabela : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoAtributoAdicionalField;
        
        private int CodigoEmpresaField;
        
        private int CodigoItemField;
        
        private string DescricaoItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoAtributoAdicional {
            get {
                return this.CodigoAtributoAdicionalField;
            }
            set {
                if ((this.CodigoAtributoAdicionalField.Equals(value) != true)) {
                    this.CodigoAtributoAdicionalField = value;
                    this.RaisePropertyChanged("CodigoAtributoAdicional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoEmpresa {
            get {
                return this.CodigoEmpresaField;
            }
            set {
                if ((this.CodigoEmpresaField.Equals(value) != true)) {
                    this.CodigoEmpresaField = value;
                    this.RaisePropertyChanged("CodigoEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoItem {
            get {
                return this.CodigoItemField;
            }
            set {
                if ((this.CodigoItemField.Equals(value) != true)) {
                    this.CodigoItemField = value;
                    this.RaisePropertyChanged("CodigoItem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DescricaoItem {
            get {
                return this.DescricaoItemField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoItemField, value) != true)) {
                    this.DescricaoItemField = value;
                    this.RaisePropertyChanged("DescricaoItem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class ListaDeInconsistencias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.Inconsistencia[] InconsistenciasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.Inconsistencia[] Inconsistencias {
            get {
                return this.InconsistenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.InconsistenciasField, value) != true)) {
                    this.InconsistenciasField = value;
                    this.RaisePropertyChanged("Inconsistencias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class Inconsistencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AtributoRelacionadoField;
        
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtributoRelacionado {
            get {
                return this.AtributoRelacionadoField;
            }
            set {
                if ((object.ReferenceEquals(this.AtributoRelacionadoField, value) != true)) {
                    this.AtributoRelacionadoField = value;
                    this.RaisePropertyChanged("AtributoRelacionado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class FalhaInternaDeExecucao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorField, value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class FalhaDePermissao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemAtributoAdicionalTipoTabela_Exclusao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class ItemAtributoAdicionalTipoTabela_Exclusao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoAtributoAdicionalField;
        
        private int CodigoEmpresaField;
        
        private int CodigoItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoAtributoAdicional {
            get {
                return this.CodigoAtributoAdicionalField;
            }
            set {
                if ((this.CodigoAtributoAdicionalField.Equals(value) != true)) {
                    this.CodigoAtributoAdicionalField = value;
                    this.RaisePropertyChanged("CodigoAtributoAdicional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoEmpresa {
            get {
                return this.CodigoEmpresaField;
            }
            set {
                if ((this.CodigoEmpresaField.Equals(value) != true)) {
                    this.CodigoEmpresaField = value;
                    this.RaisePropertyChanged("CodigoEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoItem {
            get {
                return this.CodigoItemField;
            }
            set {
                if ((this.CodigoItemField.Equals(value) != true)) {
                    this.CodigoItemField = value;
                    this.RaisePropertyChanged("CodigoItem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="lg.com.br/svc", ConfigurationName="ServicoDeItemAtributoAdicionalTipoTabela_20171.ServicoDeItemAtributoAdicionalTipo" +
        "Tabela")]
    public interface ServicoDeItemAtributoAdicionalTipoTabela {
        
        // CODEGEN: Generating message contract since message CadastreItemAtributoAdicionalRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/CadastreItemAtributoAdicio" +
            "nal", ReplyAction="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/CadastreItemAtributoAdicio" +
            "nalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/CadastreItemAtributoAdicio" +
            "nalListaDeInconsistenciasFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/CadastreItemAtributoAdicio" +
            "nalInconsistenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/CadastreItemAtributoAdicio" +
            "nalFalhaInternaDeExecucaoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/CadastreItemAtributoAdicio" +
            "nalFalhaDePermissaoFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.CadastreItemAtributoAdicionalResponse CadastreItemAtributoAdicional(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.CadastreItemAtributoAdicionalRequest request);
        
        // CODEGEN: Generating message contract since message AtualizeItemAtributoAdicionalRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/AtualizeItemAtributoAdicio" +
            "nal", ReplyAction="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/AtualizeItemAtributoAdicio" +
            "nalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/AtualizeItemAtributoAdicio" +
            "nalInconsistenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/AtualizeItemAtributoAdicio" +
            "nalListaDeInconsistenciasFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/AtualizeItemAtributoAdicio" +
            "nalFalhaInternaDeExecucaoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/AtualizeItemAtributoAdicio" +
            "nalFalhaDePermissaoFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.AtualizeItemAtributoAdicionalResponse AtualizeItemAtributoAdicional(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.AtualizeItemAtributoAdicionalRequest request);
        
        // CODEGEN: Generating message contract since message ExcluaItemAtributoAdicionalRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/ExcluaItemAtributoAdiciona" +
            "l", ReplyAction="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/ExcluaItemAtributoAdiciona" +
            "lResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/ExcluaItemAtributoAdiciona" +
            "lListaDeInconsistenciasFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/ExcluaItemAtributoAdiciona" +
            "lInconsistenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/ExcluaItemAtributoAdiciona" +
            "lFalhaInternaDeExecucaoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/ExcluaItemAtributoAdiciona" +
            "lFalhaDePermissaoFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ExcluaItemAtributoAdicionalResponse ExcluaItemAtributoAdicional(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ExcluaItemAtributoAdicionalRequest request);
        
        // CODEGEN: Generating message contract since message ConsulteItemAtributoAdicionalRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/ConsulteItemAtributoAdicio" +
            "nal", ReplyAction="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/ConsulteItemAtributoAdicio" +
            "nalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/ConsulteItemAtributoAdicio" +
            "nalInconsistenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/ConsulteItemAtributoAdicio" +
            "nalListaDeInconsistenciasFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/ConsulteItemAtributoAdicio" +
            "nalFalhaInternaDeExecucaoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeItemAtributoAdicionalTipoTabela/ConsulteItemAtributoAdicio" +
            "nalFalhaDePermissaoFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ConsulteItemAtributoAdicionalResponse ConsulteItemAtributoAdicional(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ConsulteItemAtributoAdicionalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CadastreItemAtributoAdicional", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class CadastreItemAtributoAdicionalRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ItemAtributoAdicionalTipoTabela ItemAtributoAdcional;
        
        public CadastreItemAtributoAdicionalRequest() {
        }
        
        public CadastreItemAtributoAdicionalRequest(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ItemAtributoAdicionalTipoTabela ItemAtributoAdcional) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.ItemAtributoAdcional = ItemAtributoAdcional;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CadastreItemAtributoAdicionalResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class CadastreItemAtributoAdicionalResponse {
        
        public CadastreItemAtributoAdicionalResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AtualizeItemAtributoAdicional", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class AtualizeItemAtributoAdicionalRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ItemAtributoAdicionalTipoTabela ItemAtributoAdcional;
        
        public AtualizeItemAtributoAdicionalRequest() {
        }
        
        public AtualizeItemAtributoAdicionalRequest(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ItemAtributoAdicionalTipoTabela ItemAtributoAdcional) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.ItemAtributoAdcional = ItemAtributoAdcional;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AtualizeItemAtributoAdicionalResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class AtualizeItemAtributoAdicionalResponse {
        
        public AtualizeItemAtributoAdicionalResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExcluaItemAtributoAdicional", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ExcluaItemAtributoAdicionalRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ItemAtributoAdicionalTipoTabela_Exclusao ItemAtributoAdcional_exclusao;
        
        public ExcluaItemAtributoAdicionalRequest() {
        }
        
        public ExcluaItemAtributoAdicionalRequest(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ItemAtributoAdicionalTipoTabela_Exclusao ItemAtributoAdcional_exclusao) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.ItemAtributoAdcional_exclusao = ItemAtributoAdcional_exclusao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExcluaItemAtributoAdicionalResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ExcluaItemAtributoAdicionalResponse {
        
        public ExcluaItemAtributoAdicionalResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsulteItemAtributoAdicional", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ConsulteItemAtributoAdicionalRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public int CodigoEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=1)]
        public int CodigoAtributoAdicionalTipoTabela;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=2)]
        public int CodigoItem;
        
        public ConsulteItemAtributoAdicionalRequest() {
        }
        
        public ConsulteItemAtributoAdicionalRequest(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresa, int CodigoAtributoAdicionalTipoTabela, int CodigoItem) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.CodigoEmpresa = CodigoEmpresa;
            this.CodigoAtributoAdicionalTipoTabela = CodigoAtributoAdicionalTipoTabela;
            this.CodigoItem = CodigoItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsulteItemAtributoAdicionalResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ConsulteItemAtributoAdicionalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ItemAtributoAdicionalTipoTabela ConsulteItemAtributoAdicionalResult;
        
        public ConsulteItemAtributoAdicionalResponse() {
        }
        
        public ConsulteItemAtributoAdicionalResponse(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ItemAtributoAdicionalTipoTabela ConsulteItemAtributoAdicionalResult) {
            this.ConsulteItemAtributoAdicionalResult = ConsulteItemAtributoAdicionalResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoDeItemAtributoAdicionalTipoTabelaChannel : WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ServicoDeItemAtributoAdicionalTipoTabela, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoDeItemAtributoAdicionalTipoTabelaClient : System.ServiceModel.ClientBase<WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ServicoDeItemAtributoAdicionalTipoTabela>, WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ServicoDeItemAtributoAdicionalTipoTabela {
        
        public ServicoDeItemAtributoAdicionalTipoTabelaClient() {
        }
        
        public ServicoDeItemAtributoAdicionalTipoTabelaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoDeItemAtributoAdicionalTipoTabelaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoDeItemAtributoAdicionalTipoTabelaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoDeItemAtributoAdicionalTipoTabelaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.CadastreItemAtributoAdicionalResponse WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ServicoDeItemAtributoAdicionalTipoTabela.CadastreItemAtributoAdicional(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.CadastreItemAtributoAdicionalRequest request) {
            return base.Channel.CadastreItemAtributoAdicional(request);
        }
        
        public void CadastreItemAtributoAdicional(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ItemAtributoAdicionalTipoTabela ItemAtributoAdcional) {
            WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.CadastreItemAtributoAdicionalRequest inValue = new WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.CadastreItemAtributoAdicionalRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.ItemAtributoAdcional = ItemAtributoAdcional;
            WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.CadastreItemAtributoAdicionalResponse retVal = ((WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ServicoDeItemAtributoAdicionalTipoTabela)(this)).CadastreItemAtributoAdicional(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.AtualizeItemAtributoAdicionalResponse WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ServicoDeItemAtributoAdicionalTipoTabela.AtualizeItemAtributoAdicional(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.AtualizeItemAtributoAdicionalRequest request) {
            return base.Channel.AtualizeItemAtributoAdicional(request);
        }
        
        public void AtualizeItemAtributoAdicional(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ItemAtributoAdicionalTipoTabela ItemAtributoAdcional) {
            WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.AtualizeItemAtributoAdicionalRequest inValue = new WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.AtualizeItemAtributoAdicionalRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.ItemAtributoAdcional = ItemAtributoAdcional;
            WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.AtualizeItemAtributoAdicionalResponse retVal = ((WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ServicoDeItemAtributoAdicionalTipoTabela)(this)).AtualizeItemAtributoAdicional(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ExcluaItemAtributoAdicionalResponse WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ServicoDeItemAtributoAdicionalTipoTabela.ExcluaItemAtributoAdicional(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ExcluaItemAtributoAdicionalRequest request) {
            return base.Channel.ExcluaItemAtributoAdicional(request);
        }
        
        public void ExcluaItemAtributoAdicional(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ItemAtributoAdicionalTipoTabela_Exclusao ItemAtributoAdcional_exclusao) {
            WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ExcluaItemAtributoAdicionalRequest inValue = new WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ExcluaItemAtributoAdicionalRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.ItemAtributoAdcional_exclusao = ItemAtributoAdcional_exclusao;
            WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ExcluaItemAtributoAdicionalResponse retVal = ((WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ServicoDeItemAtributoAdicionalTipoTabela)(this)).ExcluaItemAtributoAdicional(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ConsulteItemAtributoAdicionalResponse WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ServicoDeItemAtributoAdicionalTipoTabela.ConsulteItemAtributoAdicional(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ConsulteItemAtributoAdicionalRequest request) {
            return base.Channel.ConsulteItemAtributoAdicional(request);
        }
        
        public WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ItemAtributoAdicionalTipoTabela ConsulteItemAtributoAdicional(WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresa, int CodigoAtributoAdicionalTipoTabela, int CodigoItem) {
            WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ConsulteItemAtributoAdicionalRequest inValue = new WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ConsulteItemAtributoAdicionalRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.CodigoEmpresa = CodigoEmpresa;
            inValue.CodigoAtributoAdicionalTipoTabela = CodigoAtributoAdicionalTipoTabela;
            inValue.CodigoItem = CodigoItem;
            WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ConsulteItemAtributoAdicionalResponse retVal = ((WCFTestClient.Dominio.ServicoDeItemAtributoAdicionalTipoTabela_20171.ServicoDeItemAtributoAdicionalTipoTabela)(this)).ConsulteItemAtributoAdicional(inValue);
            return retVal.ConsulteItemAtributoAdicionalResult;
        }
    }
}
