//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTestClient.Dominio.ServicoDeMunicipio_20171 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGContextoAmbiente", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGContextoAmbiente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AmbienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuncaoEmExecucaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAuditoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutenticacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutenticacao_v2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutorizacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChaveContaArmazenamentoTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeContaArmazenamentoTenantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Ambiente {
            get {
                return this.AmbienteField;
            }
            set {
                if ((this.AmbienteField.Equals(value) != true)) {
                    this.AmbienteField = value;
                    this.RaisePropertyChanged("Ambiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoHost {
            get {
                return this.EnderecoHostField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoHostField, value) != true)) {
                    this.EnderecoHostField = value;
                    this.RaisePropertyChanged("EnderecoHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FuncaoEmExecucao {
            get {
                return this.FuncaoEmExecucaoField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncaoEmExecucaoField, value) != true)) {
                    this.FuncaoEmExecucaoField = value;
                    this.RaisePropertyChanged("FuncaoEmExecucao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdTenant {
            get {
                return this.IdTenantField;
            }
            set {
                if ((this.IdTenantField.Equals(value) != true)) {
                    this.IdTenantField = value;
                    this.RaisePropertyChanged("IdTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAuditoria {
            get {
                return this.IdentificadorDeAuditoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAuditoriaField, value) != true)) {
                    this.IdentificadorDeAuditoriaField = value;
                    this.RaisePropertyChanged("IdentificadorDeAuditoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutenticacao {
            get {
                return this.IdentificadorDeAutenticacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutenticacaoField, value) != true)) {
                    this.IdentificadorDeAutenticacaoField = value;
                    this.RaisePropertyChanged("IdentificadorDeAutenticacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutenticacao_v2 {
            get {
                return this.IdentificadorDeAutenticacao_v2Field;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutenticacao_v2Field, value) != true)) {
                    this.IdentificadorDeAutenticacao_v2Field = value;
                    this.RaisePropertyChanged("IdentificadorDeAutenticacao_v2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutorizacao {
            get {
                return this.IdentificadorDeAutorizacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutorizacaoField, value) != true)) {
                    this.IdentificadorDeAutorizacaoField = value;
                    this.RaisePropertyChanged("IdentificadorDeAutorizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeHost {
            get {
                return this.NomeHostField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeHostField, value) != true)) {
                    this.NomeHostField = value;
                    this.RaisePropertyChanged("NomeHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeTenant {
            get {
                return this.NomeTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeTenantField, value) != true)) {
                    this.NomeTenantField = value;
                    this.RaisePropertyChanged("NomeTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string ChaveContaArmazenamentoTenant {
            get {
                return this.ChaveContaArmazenamentoTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveContaArmazenamentoTenantField, value) != true)) {
                    this.ChaveContaArmazenamentoTenantField = value;
                    this.RaisePropertyChanged("ChaveContaArmazenamentoTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string GuidTenant {
            get {
                return this.GuidTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidTenantField, value) != true)) {
                    this.GuidTenantField = value;
                    this.RaisePropertyChanged("GuidTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string NomeContaArmazenamentoTenant {
            get {
                return this.NomeContaArmazenamentoTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeContaArmazenamentoTenantField, value) != true)) {
                    this.NomeContaArmazenamentoTenantField = value;
                    this.RaisePropertyChanged("NomeContaArmazenamentoTenant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGAutenticacao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGAutenticacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGTokenSessao TokenSessaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGTokenUsuario TokenUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGTokenSessao TokenSessao {
            get {
                return this.TokenSessaoField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenSessaoField, value) != true)) {
                    this.TokenSessaoField = value;
                    this.RaisePropertyChanged("TokenSessao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGTokenUsuario TokenUsuario {
            get {
                return this.TokenUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenUsuarioField, value) != true)) {
                    this.TokenUsuarioField = value;
                    this.RaisePropertyChanged("TokenUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGTokenSessao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGTokenSessao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdGerenciadorTokenField;
        
        private string IdSessaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdGerenciadorToken {
            get {
                return this.IdGerenciadorTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.IdGerenciadorTokenField, value) != true)) {
                    this.IdGerenciadorTokenField = value;
                    this.RaisePropertyChanged("IdGerenciadorToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdSessao {
            get {
                return this.IdSessaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSessaoField, value) != true)) {
                    this.IdSessaoField = value;
                    this.RaisePropertyChanged("IdSessao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGTokenUsuario", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGTokenUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SenhaField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidTenantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string GuidTenant {
            get {
                return this.GuidTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidTenantField, value) != true)) {
                    this.GuidTenantField = value;
                    this.RaisePropertyChanged("GuidTenant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Municipio", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class Municipio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CEPField;
        
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodigoCalendarioField;
        
        private string DescricaoField;
        
        private WCFTestClient.Dominio.ServicoDeMunicipio_20171.EnumUF UFField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CEP {
            get {
                return this.CEPField;
            }
            set {
                if ((this.CEPField.Equals(value) != true)) {
                    this.CEPField = value;
                    this.RaisePropertyChanged("CEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoCalendario {
            get {
                return this.CodigoCalendarioField;
            }
            set {
                if ((this.CodigoCalendarioField.Equals(value) != true)) {
                    this.CodigoCalendarioField = value;
                    this.RaisePropertyChanged("CodigoCalendario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.EnumUF UF {
            get {
                return this.UFField;
            }
            set {
                if ((this.UFField.Equals(value) != true)) {
                    this.UFField = value;
                    this.RaisePropertyChanged("UF");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumUF", Namespace="lg.com.br/svc/dto")]
    public enum EnumUF : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACRE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALAGOAS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AMAZONAS = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AMAPA = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BAHIA = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CEARA = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DISTRITO_FEDERAL = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ESPIRITO_SANTO = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GOIAS = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MARANHAO = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MINAS_GERAIS = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MATO_GROSSO_DO_SUL = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MATO_GROSSO = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PARA = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PARAIBA = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PERNAMBUCO = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PIAUI = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PARANA = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RIO_DE_JANEIRO = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RIO_GRANDE_DO_NORTE = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RONDONIA = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RORAIMA = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RIO_GRANDE_DO_SUL = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SANTA_CATARINA = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SERGIPE = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SAO_PAULO = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TOCANTINS = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OUTROS = 27,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class Inconsistencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AtributoRelacionadoField;
        
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtributoRelacionado {
            get {
                return this.AtributoRelacionadoField;
            }
            set {
                if ((object.ReferenceEquals(this.AtributoRelacionadoField, value) != true)) {
                    this.AtributoRelacionadoField = value;
                    this.RaisePropertyChanged("AtributoRelacionado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class ListaDeInconsistencias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WCFTestClient.Dominio.ServicoDeMunicipio_20171.Inconsistencia[] InconsistenciasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.Inconsistencia[] Inconsistencias {
            get {
                return this.InconsistenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.InconsistenciasField, value) != true)) {
                    this.InconsistenciasField = value;
                    this.RaisePropertyChanged("Inconsistencias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class FalhaInternaDeExecucao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorField, value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class FalhaDePermissao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Municipio_Exclusao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class Municipio_Exclusao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="lg.com.br/svc", ConfigurationName="ServicoDeMunicipio_20171.ServicoDeMunicipio")]
    public interface ServicoDeMunicipio {
        
        // CODEGEN: Generating message contract since message CadastreMunicipioRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeMunicipio/CadastreMunicipio", ReplyAction="lg.com.br/svc/ServicoDeMunicipio/CadastreMunicipioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeMunicipio/CadastreMunicipioInconsistenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeMunicipio/CadastreMunicipioListaDeInconsistenciasFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeMunicipio/CadastreMunicipioFalhaInternaDeExecucaoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeMunicipio/CadastreMunicipioFalhaDePermissaoFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeMunicipio_20171.CadastreMunicipioResponse CadastreMunicipio(WCFTestClient.Dominio.ServicoDeMunicipio_20171.CadastreMunicipioRequest request);
        
        // CODEGEN: Generating message contract since message AtualizeMunicipioRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeMunicipio/AtualizeMunicipio", ReplyAction="lg.com.br/svc/ServicoDeMunicipio/AtualizeMunicipioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeMunicipio/AtualizeMunicipioInconsistenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeMunicipio/AtualizeMunicipioListaDeInconsistenciasFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeMunicipio/AtualizeMunicipioFalhaInternaDeExecucaoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeMunicipio/AtualizeMunicipioFalhaDePermissaoFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeMunicipio_20171.AtualizeMunicipioResponse AtualizeMunicipio(WCFTestClient.Dominio.ServicoDeMunicipio_20171.AtualizeMunicipioRequest request);
        
        // CODEGEN: Generating message contract since message ExcluaMunicipioRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeMunicipio/ExcluaMunicipio", ReplyAction="lg.com.br/svc/ServicoDeMunicipio/ExcluaMunicipioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeMunicipio/ExcluaMunicipioListaDeInconsistenciasFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeMunicipio/ExcluaMunicipioInconsistenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeMunicipio/ExcluaMunicipioFalhaInternaDeExecucaoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeMunicipio/ExcluaMunicipioFalhaDePermissaoFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeMunicipio_20171.ExcluaMunicipioResponse ExcluaMunicipio(WCFTestClient.Dominio.ServicoDeMunicipio_20171.ExcluaMunicipioRequest request);
        
        // CODEGEN: Generating message contract since message ConsulteMunicipioRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeMunicipio/ConsulteMunicipio", ReplyAction="lg.com.br/svc/ServicoDeMunicipio/ConsulteMunicipioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeMunicipio/ConsulteMunicipioInconsistenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeMunicipio/ConsulteMunicipioListaDeInconsistenciasFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeMunicipio/ConsulteMunicipioFalhaInternaDeExecucaoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeMunicipio/ConsulteMunicipioFalhaDePermissaoFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeMunicipio_20171.ConsulteMunicipioResponse ConsulteMunicipio(WCFTestClient.Dominio.ServicoDeMunicipio_20171.ConsulteMunicipioRequest request);
        
        // CODEGEN: Generating message contract since message ConsulteListaMunicipiosPorUFRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeMunicipio/ConsulteListaMunicipiosPorUF", ReplyAction="lg.com.br/svc/ServicoDeMunicipio/ConsulteListaMunicipiosPorUFResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeMunicipio/ConsulteListaMunicipiosPorUFListaDeInconsistenci" +
            "asFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeMunicipio/ConsulteListaMunicipiosPorUFInconsistenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeMunicipio/ConsulteListaMunicipiosPorUFFalhaInternaDeExecuc" +
            "aoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeMunicipio_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeMunicipio/ConsulteListaMunicipiosPorUFFalhaDePermissaoFaul" +
            "t", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeMunicipio_20171.ConsulteListaMunicipiosPorUFResponse ConsulteListaMunicipiosPorUF(WCFTestClient.Dominio.ServicoDeMunicipio_20171.ConsulteListaMunicipiosPorUFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CadastreMunicipio", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class CadastreMunicipioRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public int CodigoEmpresaAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=1)]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.Municipio municipio;
        
        public CadastreMunicipioRequest() {
        }
        
        public CadastreMunicipioRequest(WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaAutenticacao, WCFTestClient.Dominio.ServicoDeMunicipio_20171.Municipio municipio) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.CodigoEmpresaAutenticacao = CodigoEmpresaAutenticacao;
            this.municipio = municipio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CadastreMunicipioResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class CadastreMunicipioResponse {
        
        public CadastreMunicipioResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AtualizeMunicipio", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class AtualizeMunicipioRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public int CodigoEmpresaAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=1)]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.Municipio municipio;
        
        public AtualizeMunicipioRequest() {
        }
        
        public AtualizeMunicipioRequest(WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaAutenticacao, WCFTestClient.Dominio.ServicoDeMunicipio_20171.Municipio municipio) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.CodigoEmpresaAutenticacao = CodigoEmpresaAutenticacao;
            this.municipio = municipio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AtualizeMunicipioResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class AtualizeMunicipioResponse {
        
        public AtualizeMunicipioResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExcluaMunicipio", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ExcluaMunicipioRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public int CodigoEmpresaAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=1)]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.Municipio_Exclusao municipio;
        
        public ExcluaMunicipioRequest() {
        }
        
        public ExcluaMunicipioRequest(WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaAutenticacao, WCFTestClient.Dominio.ServicoDeMunicipio_20171.Municipio_Exclusao municipio) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.CodigoEmpresaAutenticacao = CodigoEmpresaAutenticacao;
            this.municipio = municipio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExcluaMunicipioResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ExcluaMunicipioResponse {
        
        public ExcluaMunicipioResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsulteMunicipio", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ConsulteMunicipioRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public int CodigoEmpresaAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=1)]
        public int CodigoMunicipio;
        
        public ConsulteMunicipioRequest() {
        }
        
        public ConsulteMunicipioRequest(WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaAutenticacao, int CodigoMunicipio) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.CodigoEmpresaAutenticacao = CodigoEmpresaAutenticacao;
            this.CodigoMunicipio = CodigoMunicipio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsulteMunicipioResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ConsulteMunicipioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.Municipio ConsulteMunicipioResult;
        
        public ConsulteMunicipioResponse() {
        }
        
        public ConsulteMunicipioResponse(WCFTestClient.Dominio.ServicoDeMunicipio_20171.Municipio ConsulteMunicipioResult) {
            this.ConsulteMunicipioResult = ConsulteMunicipioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsulteListaMunicipiosPorUF", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ConsulteListaMunicipiosPorUFRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public int CodigoEmpresaAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=1)]
        public string UF;
        
        public ConsulteListaMunicipiosPorUFRequest() {
        }
        
        public ConsulteListaMunicipiosPorUFRequest(WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaAutenticacao, string UF) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.CodigoEmpresaAutenticacao = CodigoEmpresaAutenticacao;
            this.UF = UF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsulteListaMunicipiosPorUFResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ConsulteListaMunicipiosPorUFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.Municipio[] ConsulteListaMunicipiosPorUFResult;
        
        public ConsulteListaMunicipiosPorUFResponse() {
        }
        
        public ConsulteListaMunicipiosPorUFResponse(WCFTestClient.Dominio.ServicoDeMunicipio_20171.Municipio[] ConsulteListaMunicipiosPorUFResult) {
            this.ConsulteListaMunicipiosPorUFResult = ConsulteListaMunicipiosPorUFResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoDeMunicipioChannel : WCFTestClient.Dominio.ServicoDeMunicipio_20171.ServicoDeMunicipio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoDeMunicipioClient : System.ServiceModel.ClientBase<WCFTestClient.Dominio.ServicoDeMunicipio_20171.ServicoDeMunicipio>, WCFTestClient.Dominio.ServicoDeMunicipio_20171.ServicoDeMunicipio {
        
        public ServicoDeMunicipioClient() {
        }
        
        public ServicoDeMunicipioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoDeMunicipioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoDeMunicipioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoDeMunicipioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeMunicipio_20171.CadastreMunicipioResponse WCFTestClient.Dominio.ServicoDeMunicipio_20171.ServicoDeMunicipio.CadastreMunicipio(WCFTestClient.Dominio.ServicoDeMunicipio_20171.CadastreMunicipioRequest request) {
            return base.Channel.CadastreMunicipio(request);
        }
        
        public void CadastreMunicipio(WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaAutenticacao, WCFTestClient.Dominio.ServicoDeMunicipio_20171.Municipio municipio) {
            WCFTestClient.Dominio.ServicoDeMunicipio_20171.CadastreMunicipioRequest inValue = new WCFTestClient.Dominio.ServicoDeMunicipio_20171.CadastreMunicipioRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.CodigoEmpresaAutenticacao = CodigoEmpresaAutenticacao;
            inValue.municipio = municipio;
            WCFTestClient.Dominio.ServicoDeMunicipio_20171.CadastreMunicipioResponse retVal = ((WCFTestClient.Dominio.ServicoDeMunicipio_20171.ServicoDeMunicipio)(this)).CadastreMunicipio(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeMunicipio_20171.AtualizeMunicipioResponse WCFTestClient.Dominio.ServicoDeMunicipio_20171.ServicoDeMunicipio.AtualizeMunicipio(WCFTestClient.Dominio.ServicoDeMunicipio_20171.AtualizeMunicipioRequest request) {
            return base.Channel.AtualizeMunicipio(request);
        }
        
        public void AtualizeMunicipio(WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaAutenticacao, WCFTestClient.Dominio.ServicoDeMunicipio_20171.Municipio municipio) {
            WCFTestClient.Dominio.ServicoDeMunicipio_20171.AtualizeMunicipioRequest inValue = new WCFTestClient.Dominio.ServicoDeMunicipio_20171.AtualizeMunicipioRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.CodigoEmpresaAutenticacao = CodigoEmpresaAutenticacao;
            inValue.municipio = municipio;
            WCFTestClient.Dominio.ServicoDeMunicipio_20171.AtualizeMunicipioResponse retVal = ((WCFTestClient.Dominio.ServicoDeMunicipio_20171.ServicoDeMunicipio)(this)).AtualizeMunicipio(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeMunicipio_20171.ExcluaMunicipioResponse WCFTestClient.Dominio.ServicoDeMunicipio_20171.ServicoDeMunicipio.ExcluaMunicipio(WCFTestClient.Dominio.ServicoDeMunicipio_20171.ExcluaMunicipioRequest request) {
            return base.Channel.ExcluaMunicipio(request);
        }
        
        public void ExcluaMunicipio(WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaAutenticacao, WCFTestClient.Dominio.ServicoDeMunicipio_20171.Municipio_Exclusao municipio) {
            WCFTestClient.Dominio.ServicoDeMunicipio_20171.ExcluaMunicipioRequest inValue = new WCFTestClient.Dominio.ServicoDeMunicipio_20171.ExcluaMunicipioRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.CodigoEmpresaAutenticacao = CodigoEmpresaAutenticacao;
            inValue.municipio = municipio;
            WCFTestClient.Dominio.ServicoDeMunicipio_20171.ExcluaMunicipioResponse retVal = ((WCFTestClient.Dominio.ServicoDeMunicipio_20171.ServicoDeMunicipio)(this)).ExcluaMunicipio(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeMunicipio_20171.ConsulteMunicipioResponse WCFTestClient.Dominio.ServicoDeMunicipio_20171.ServicoDeMunicipio.ConsulteMunicipio(WCFTestClient.Dominio.ServicoDeMunicipio_20171.ConsulteMunicipioRequest request) {
            return base.Channel.ConsulteMunicipio(request);
        }
        
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.Municipio ConsulteMunicipio(WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaAutenticacao, int CodigoMunicipio) {
            WCFTestClient.Dominio.ServicoDeMunicipio_20171.ConsulteMunicipioRequest inValue = new WCFTestClient.Dominio.ServicoDeMunicipio_20171.ConsulteMunicipioRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.CodigoEmpresaAutenticacao = CodigoEmpresaAutenticacao;
            inValue.CodigoMunicipio = CodigoMunicipio;
            WCFTestClient.Dominio.ServicoDeMunicipio_20171.ConsulteMunicipioResponse retVal = ((WCFTestClient.Dominio.ServicoDeMunicipio_20171.ServicoDeMunicipio)(this)).ConsulteMunicipio(inValue);
            return retVal.ConsulteMunicipioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeMunicipio_20171.ConsulteListaMunicipiosPorUFResponse WCFTestClient.Dominio.ServicoDeMunicipio_20171.ServicoDeMunicipio.ConsulteListaMunicipiosPorUF(WCFTestClient.Dominio.ServicoDeMunicipio_20171.ConsulteListaMunicipiosPorUFRequest request) {
            return base.Channel.ConsulteListaMunicipiosPorUF(request);
        }
        
        public WCFTestClient.Dominio.ServicoDeMunicipio_20171.Municipio[] ConsulteListaMunicipiosPorUF(WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeMunicipio_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresaAutenticacao, string UF) {
            WCFTestClient.Dominio.ServicoDeMunicipio_20171.ConsulteListaMunicipiosPorUFRequest inValue = new WCFTestClient.Dominio.ServicoDeMunicipio_20171.ConsulteListaMunicipiosPorUFRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.CodigoEmpresaAutenticacao = CodigoEmpresaAutenticacao;
            inValue.UF = UF;
            WCFTestClient.Dominio.ServicoDeMunicipio_20171.ConsulteListaMunicipiosPorUFResponse retVal = ((WCFTestClient.Dominio.ServicoDeMunicipio_20171.ServicoDeMunicipio)(this)).ConsulteListaMunicipiosPorUF(inValue);
            return retVal.ConsulteListaMunicipiosPorUFResult;
        }
    }
}
