//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTestClient.Dominio.ServicoDeSituacao_20171 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGContextoAmbiente", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGContextoAmbiente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AmbienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuncaoEmExecucaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAuditoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutenticacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutenticacao_v2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutorizacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChaveContaArmazenamentoTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeContaArmazenamentoTenantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Ambiente {
            get {
                return this.AmbienteField;
            }
            set {
                if ((this.AmbienteField.Equals(value) != true)) {
                    this.AmbienteField = value;
                    this.RaisePropertyChanged("Ambiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoHost {
            get {
                return this.EnderecoHostField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoHostField, value) != true)) {
                    this.EnderecoHostField = value;
                    this.RaisePropertyChanged("EnderecoHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FuncaoEmExecucao {
            get {
                return this.FuncaoEmExecucaoField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncaoEmExecucaoField, value) != true)) {
                    this.FuncaoEmExecucaoField = value;
                    this.RaisePropertyChanged("FuncaoEmExecucao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdTenant {
            get {
                return this.IdTenantField;
            }
            set {
                if ((this.IdTenantField.Equals(value) != true)) {
                    this.IdTenantField = value;
                    this.RaisePropertyChanged("IdTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAuditoria {
            get {
                return this.IdentificadorDeAuditoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAuditoriaField, value) != true)) {
                    this.IdentificadorDeAuditoriaField = value;
                    this.RaisePropertyChanged("IdentificadorDeAuditoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutenticacao {
            get {
                return this.IdentificadorDeAutenticacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutenticacaoField, value) != true)) {
                    this.IdentificadorDeAutenticacaoField = value;
                    this.RaisePropertyChanged("IdentificadorDeAutenticacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutenticacao_v2 {
            get {
                return this.IdentificadorDeAutenticacao_v2Field;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutenticacao_v2Field, value) != true)) {
                    this.IdentificadorDeAutenticacao_v2Field = value;
                    this.RaisePropertyChanged("IdentificadorDeAutenticacao_v2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutorizacao {
            get {
                return this.IdentificadorDeAutorizacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutorizacaoField, value) != true)) {
                    this.IdentificadorDeAutorizacaoField = value;
                    this.RaisePropertyChanged("IdentificadorDeAutorizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeHost {
            get {
                return this.NomeHostField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeHostField, value) != true)) {
                    this.NomeHostField = value;
                    this.RaisePropertyChanged("NomeHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeTenant {
            get {
                return this.NomeTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeTenantField, value) != true)) {
                    this.NomeTenantField = value;
                    this.RaisePropertyChanged("NomeTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string ChaveContaArmazenamentoTenant {
            get {
                return this.ChaveContaArmazenamentoTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveContaArmazenamentoTenantField, value) != true)) {
                    this.ChaveContaArmazenamentoTenantField = value;
                    this.RaisePropertyChanged("ChaveContaArmazenamentoTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string GuidTenant {
            get {
                return this.GuidTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidTenantField, value) != true)) {
                    this.GuidTenantField = value;
                    this.RaisePropertyChanged("GuidTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string NomeContaArmazenamentoTenant {
            get {
                return this.NomeContaArmazenamentoTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeContaArmazenamentoTenantField, value) != true)) {
                    this.NomeContaArmazenamentoTenantField = value;
                    this.RaisePropertyChanged("NomeContaArmazenamentoTenant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGAutenticacao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGAutenticacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTestClient.Dominio.ServicoDeSituacao_20171.LGTokenSessao TokenSessaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTestClient.Dominio.ServicoDeSituacao_20171.LGTokenUsuario TokenUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFTestClient.Dominio.ServicoDeSituacao_20171.LGTokenSessao TokenSessao {
            get {
                return this.TokenSessaoField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenSessaoField, value) != true)) {
                    this.TokenSessaoField = value;
                    this.RaisePropertyChanged("TokenSessao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFTestClient.Dominio.ServicoDeSituacao_20171.LGTokenUsuario TokenUsuario {
            get {
                return this.TokenUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenUsuarioField, value) != true)) {
                    this.TokenUsuarioField = value;
                    this.RaisePropertyChanged("TokenUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGTokenSessao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGTokenSessao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdGerenciadorTokenField;
        
        private string IdSessaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdGerenciadorToken {
            get {
                return this.IdGerenciadorTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.IdGerenciadorTokenField, value) != true)) {
                    this.IdGerenciadorTokenField = value;
                    this.RaisePropertyChanged("IdGerenciadorToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdSessao {
            get {
                return this.IdSessaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSessaoField, value) != true)) {
                    this.IdSessaoField = value;
                    this.RaisePropertyChanged("IdSessao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGTokenUsuario", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGTokenUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SenhaField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidTenantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string GuidTenant {
            get {
                return this.GuidTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidTenantField, value) != true)) {
                    this.GuidTenantField = value;
                    this.RaisePropertyChanged("GuidTenant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaSituacao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class EmpresaSituacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumTipoSituacao", Namespace="lg.com.br/svc/dto")]
    public enum EnumTipoSituacao : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ATIVIDADE_NORMAL = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FERIAS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AFASTAMENTO = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESCISAO = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RECESSO = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SituacaoRecesso", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class SituacaoRecesso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoSituacaoField;
        
        private string DescricaoSituacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoSituacao {
            get {
                return this.CodigoSituacaoField;
            }
            set {
                if ((this.CodigoSituacaoField.Equals(value) != true)) {
                    this.CodigoSituacaoField = value;
                    this.RaisePropertyChanged("CodigoSituacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DescricaoSituacao {
            get {
                return this.DescricaoSituacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoSituacaoField, value) != true)) {
                    this.DescricaoSituacaoField = value;
                    this.RaisePropertyChanged("DescricaoSituacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class ListaDeInconsistencias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WCFTestClient.Dominio.ServicoDeSituacao_20171.Inconsistencia[] InconsistenciasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFTestClient.Dominio.ServicoDeSituacao_20171.Inconsistencia[] Inconsistencias {
            get {
                return this.InconsistenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.InconsistenciasField, value) != true)) {
                    this.InconsistenciasField = value;
                    this.RaisePropertyChanged("Inconsistencias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class Inconsistencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AtributoRelacionadoField;
        
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtributoRelacionado {
            get {
                return this.AtributoRelacionadoField;
            }
            set {
                if ((object.ReferenceEquals(this.AtributoRelacionadoField, value) != true)) {
                    this.AtributoRelacionadoField = value;
                    this.RaisePropertyChanged("AtributoRelacionado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class FalhaInternaDeExecucao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorField, value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class FalhaDePermissao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="lg.com.br/svc", ConfigurationName="ServicoDeSituacao_20171.ServicoDeSituacao")]
    public interface ServicoDeSituacao {
        
        // CODEGEN: Generating message contract since message ConsulteSituacaoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeSituacao/ConsulteSituacao", ReplyAction="lg.com.br/svc/ServicoDeSituacao/ConsulteSituacaoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeSituacao_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeSituacao/ConsulteSituacaoListaDeInconsistenciasFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeSituacao_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeSituacao/ConsulteSituacaoInconsistenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeSituacao_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeSituacao/ConsulteSituacaoFalhaInternaDeExecucaoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeSituacao_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeSituacao/ConsulteSituacaoFalhaDePermissaoFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeSituacao_20171.ConsulteSituacaoResponse ConsulteSituacao(WCFTestClient.Dominio.ServicoDeSituacao_20171.ConsulteSituacaoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsulteSituacao", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ConsulteSituacaoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeSituacao_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeSituacao_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeSituacao_20171.EmpresaSituacao EmpresaSituacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=1)]
        public WCFTestClient.Dominio.ServicoDeSituacao_20171.EnumTipoSituacao TipoDaSituacao;
        
        public ConsulteSituacaoRequest() {
        }
        
        public ConsulteSituacaoRequest(WCFTestClient.Dominio.ServicoDeSituacao_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeSituacao_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeSituacao_20171.EmpresaSituacao EmpresaSituacao, WCFTestClient.Dominio.ServicoDeSituacao_20171.EnumTipoSituacao TipoDaSituacao) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.EmpresaSituacao = EmpresaSituacao;
            this.TipoDaSituacao = TipoDaSituacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsulteSituacaoResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ConsulteSituacaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeSituacao_20171.SituacaoRecesso[] ConsulteSituacaoResult;
        
        public ConsulteSituacaoResponse() {
        }
        
        public ConsulteSituacaoResponse(WCFTestClient.Dominio.ServicoDeSituacao_20171.SituacaoRecesso[] ConsulteSituacaoResult) {
            this.ConsulteSituacaoResult = ConsulteSituacaoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoDeSituacaoChannel : WCFTestClient.Dominio.ServicoDeSituacao_20171.ServicoDeSituacao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoDeSituacaoClient : System.ServiceModel.ClientBase<WCFTestClient.Dominio.ServicoDeSituacao_20171.ServicoDeSituacao>, WCFTestClient.Dominio.ServicoDeSituacao_20171.ServicoDeSituacao {
        
        public ServicoDeSituacaoClient() {
        }
        
        public ServicoDeSituacaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoDeSituacaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoDeSituacaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoDeSituacaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeSituacao_20171.ConsulteSituacaoResponse WCFTestClient.Dominio.ServicoDeSituacao_20171.ServicoDeSituacao.ConsulteSituacao(WCFTestClient.Dominio.ServicoDeSituacao_20171.ConsulteSituacaoRequest request) {
            return base.Channel.ConsulteSituacao(request);
        }
        
        public WCFTestClient.Dominio.ServicoDeSituacao_20171.SituacaoRecesso[] ConsulteSituacao(WCFTestClient.Dominio.ServicoDeSituacao_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeSituacao_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeSituacao_20171.EmpresaSituacao EmpresaSituacao, WCFTestClient.Dominio.ServicoDeSituacao_20171.EnumTipoSituacao TipoDaSituacao) {
            WCFTestClient.Dominio.ServicoDeSituacao_20171.ConsulteSituacaoRequest inValue = new WCFTestClient.Dominio.ServicoDeSituacao_20171.ConsulteSituacaoRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.EmpresaSituacao = EmpresaSituacao;
            inValue.TipoDaSituacao = TipoDaSituacao;
            WCFTestClient.Dominio.ServicoDeSituacao_20171.ConsulteSituacaoResponse retVal = ((WCFTestClient.Dominio.ServicoDeSituacao_20171.ServicoDeSituacao)(this)).ConsulteSituacao(inValue);
            return retVal.ConsulteSituacaoResult;
        }
    }
}
