//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGContextoAmbiente", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGContextoAmbiente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AmbienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuncaoEmExecucaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAuditoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutenticacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutenticacao_v2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorDeAutorizacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChaveContaArmazenamentoTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidTenantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeContaArmazenamentoTenantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Ambiente {
            get {
                return this.AmbienteField;
            }
            set {
                if ((this.AmbienteField.Equals(value) != true)) {
                    this.AmbienteField = value;
                    this.RaisePropertyChanged("Ambiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoHost {
            get {
                return this.EnderecoHostField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoHostField, value) != true)) {
                    this.EnderecoHostField = value;
                    this.RaisePropertyChanged("EnderecoHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FuncaoEmExecucao {
            get {
                return this.FuncaoEmExecucaoField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncaoEmExecucaoField, value) != true)) {
                    this.FuncaoEmExecucaoField = value;
                    this.RaisePropertyChanged("FuncaoEmExecucao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdTenant {
            get {
                return this.IdTenantField;
            }
            set {
                if ((this.IdTenantField.Equals(value) != true)) {
                    this.IdTenantField = value;
                    this.RaisePropertyChanged("IdTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAuditoria {
            get {
                return this.IdentificadorDeAuditoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAuditoriaField, value) != true)) {
                    this.IdentificadorDeAuditoriaField = value;
                    this.RaisePropertyChanged("IdentificadorDeAuditoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutenticacao {
            get {
                return this.IdentificadorDeAutenticacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutenticacaoField, value) != true)) {
                    this.IdentificadorDeAutenticacaoField = value;
                    this.RaisePropertyChanged("IdentificadorDeAutenticacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutenticacao_v2 {
            get {
                return this.IdentificadorDeAutenticacao_v2Field;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutenticacao_v2Field, value) != true)) {
                    this.IdentificadorDeAutenticacao_v2Field = value;
                    this.RaisePropertyChanged("IdentificadorDeAutenticacao_v2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorDeAutorizacao {
            get {
                return this.IdentificadorDeAutorizacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorDeAutorizacaoField, value) != true)) {
                    this.IdentificadorDeAutorizacaoField = value;
                    this.RaisePropertyChanged("IdentificadorDeAutorizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeHost {
            get {
                return this.NomeHostField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeHostField, value) != true)) {
                    this.NomeHostField = value;
                    this.RaisePropertyChanged("NomeHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeTenant {
            get {
                return this.NomeTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeTenantField, value) != true)) {
                    this.NomeTenantField = value;
                    this.RaisePropertyChanged("NomeTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string ChaveContaArmazenamentoTenant {
            get {
                return this.ChaveContaArmazenamentoTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveContaArmazenamentoTenantField, value) != true)) {
                    this.ChaveContaArmazenamentoTenantField = value;
                    this.RaisePropertyChanged("ChaveContaArmazenamentoTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string GuidTenant {
            get {
                return this.GuidTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidTenantField, value) != true)) {
                    this.GuidTenantField = value;
                    this.RaisePropertyChanged("GuidTenant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string NomeContaArmazenamentoTenant {
            get {
                return this.NomeContaArmazenamentoTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeContaArmazenamentoTenantField, value) != true)) {
                    this.NomeContaArmazenamentoTenantField = value;
                    this.RaisePropertyChanged("NomeContaArmazenamentoTenant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGAutenticacao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGAutenticacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGTokenSessao TokenSessaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGTokenUsuario TokenUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGTokenSessao TokenSessao {
            get {
                return this.TokenSessaoField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenSessaoField, value) != true)) {
                    this.TokenSessaoField = value;
                    this.RaisePropertyChanged("TokenSessao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGTokenUsuario TokenUsuario {
            get {
                return this.TokenUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenUsuarioField, value) != true)) {
                    this.TokenUsuarioField = value;
                    this.RaisePropertyChanged("TokenUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGTokenSessao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGTokenSessao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdGerenciadorTokenField;
        
        private string IdSessaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdGerenciadorToken {
            get {
                return this.IdGerenciadorTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.IdGerenciadorTokenField, value) != true)) {
                    this.IdGerenciadorTokenField = value;
                    this.RaisePropertyChanged("IdGerenciadorToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdSessao {
            get {
                return this.IdSessaoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSessaoField, value) != true)) {
                    this.IdSessaoField = value;
                    this.RaisePropertyChanged("IdSessao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LGTokenUsuario", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class LGTokenUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SenhaField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidTenantField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string GuidTenant {
            get {
                return this.GuidTenantField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidTenantField, value) != true)) {
                    this.GuidTenantField = value;
                    this.RaisePropertyChanged("GuidTenant");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvisoPrevio", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class AvisoPrevio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataAvisoPrevioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataPrevisaoRescisaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short TipoAvisoPrevioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataAvisoPrevio {
            get {
                return this.DataAvisoPrevioField;
            }
            set {
                if ((this.DataAvisoPrevioField.Equals(value) != true)) {
                    this.DataAvisoPrevioField = value;
                    this.RaisePropertyChanged("DataAvisoPrevio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataPrevisaoRescisao {
            get {
                return this.DataPrevisaoRescisaoField;
            }
            set {
                if ((this.DataPrevisaoRescisaoField.Equals(value) != true)) {
                    this.DataPrevisaoRescisaoField = value;
                    this.RaisePropertyChanged("DataPrevisaoRescisao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((this.EmpresaField.Equals(value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((this.MatriculaField.Equals(value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacao {
            get {
                return this.ObservacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacaoField, value) != true)) {
                    this.ObservacaoField = value;
                    this.RaisePropertyChanged("Observacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short TipoAvisoPrevio {
            get {
                return this.TipoAvisoPrevioField;
            }
            set {
                if ((this.TipoAvisoPrevioField.Equals(value) != true)) {
                    this.TipoAvisoPrevioField = value;
                    this.RaisePropertyChanged("TipoAvisoPrevio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class ListaDeInconsistencias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.Inconsistencia[] InconsistenciasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.Inconsistencia[] Inconsistencias {
            get {
                return this.InconsistenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.InconsistenciasField, value) != true)) {
                    this.InconsistenciasField = value;
                    this.RaisePropertyChanged("Inconsistencias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class Inconsistencia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AtributoRelacionadoField;
        
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtributoRelacionado {
            get {
                return this.AtributoRelacionadoField;
            }
            set {
                if ((object.ReferenceEquals(this.AtributoRelacionadoField, value) != true)) {
                    this.AtributoRelacionadoField = value;
                    this.RaisePropertyChanged("AtributoRelacionado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class FalhaInternaDeExecucao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorField, value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class FalhaDePermissao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InconsistenciaComCampo", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class InconsistenciaComCampo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropriedadeValidadaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropriedadeValidada {
            get {
                return this.PropriedadeValidadaField;
            }
            set {
                if ((object.ReferenceEquals(this.PropriedadeValidadaField, value) != true)) {
                    this.PropriedadeValidadaField = value;
                    this.RaisePropertyChanged("PropriedadeValidada");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoAvisoPrevio", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class TipoAvisoPrevio : WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.RetornoCodigoEDescricaoGenericoint {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoCodigoEDescricaoGenericoint", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.TipoAvisoPrevio))]
    public partial class RetornoCodigoEDescricaoGenericoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        private string DescricaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvisoPrevioConsulta", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class AvisoPrevioConsulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.AvisoPrevio AvisoPrevioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.AvisoPrevioCancelamento DadosCancelamentoAvisoPrevioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.AvisoPrevio AvisoPrevio {
            get {
                return this.AvisoPrevioField;
            }
            set {
                if ((object.ReferenceEquals(this.AvisoPrevioField, value) != true)) {
                    this.AvisoPrevioField = value;
                    this.RaisePropertyChanged("AvisoPrevio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.AvisoPrevioCancelamento DadosCancelamentoAvisoPrevio {
            get {
                return this.DadosCancelamentoAvisoPrevioField;
            }
            set {
                if ((object.ReferenceEquals(this.DadosCancelamentoAvisoPrevioField, value) != true)) {
                    this.DadosCancelamentoAvisoPrevioField = value;
                    this.RaisePropertyChanged("DadosCancelamentoAvisoPrevio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvisoPrevioCancelamento", Namespace="lg.com.br/svc/dto")]
    [System.SerializableAttribute()]
    public partial class AvisoPrevioCancelamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataAvisoPrevioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataCancelamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short MotivoCancelamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacaoCancelamentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataAvisoPrevio {
            get {
                return this.DataAvisoPrevioField;
            }
            set {
                if ((this.DataAvisoPrevioField.Equals(value) != true)) {
                    this.DataAvisoPrevioField = value;
                    this.RaisePropertyChanged("DataAvisoPrevio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataCancelamento {
            get {
                return this.DataCancelamentoField;
            }
            set {
                if ((this.DataCancelamentoField.Equals(value) != true)) {
                    this.DataCancelamentoField = value;
                    this.RaisePropertyChanged("DataCancelamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((this.EmpresaField.Equals(value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((this.MatriculaField.Equals(value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short MotivoCancelamento {
            get {
                return this.MotivoCancelamentoField;
            }
            set {
                if ((this.MotivoCancelamentoField.Equals(value) != true)) {
                    this.MotivoCancelamentoField = value;
                    this.RaisePropertyChanged("MotivoCancelamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservacaoCancelamento {
            get {
                return this.ObservacaoCancelamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacaoCancelamentoField, value) != true)) {
                    this.ObservacaoCancelamentoField = value;
                    this.RaisePropertyChanged("ObservacaoCancelamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="lg.com.br/svc", ConfigurationName="ServicoDeAvisoPrevio_20171.ServicoDeAvisoPrevio")]
    public interface ServicoDeAvisoPrevio {
        
        // CODEGEN: Generating message contract since message CadastreRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeAvisoPrevio/Cadastre", ReplyAction="lg.com.br/svc/ServicoDeAvisoPrevio/CadastreResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeAvisoPrevio/CadastreListaDeInconsistenciasFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeAvisoPrevio/CadastreInconsistenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeAvisoPrevio/CadastreFalhaInternaDeExecucaoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeAvisoPrevio/CadastreFalhaDePermissaoFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.CadastreResponse Cadastre(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.CadastreRequest request);
        
        // CODEGEN: Generating message contract since message CalculeDataDePrevisaoDaRescisaoRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeAvisoPrevio/CalculeDataDePrevisaoDaRescisao", ReplyAction="lg.com.br/svc/ServicoDeAvisoPrevio/CalculeDataDePrevisaoDaRescisaoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeAvisoPrevio/CalculeDataDePrevisaoDaRescisaoListaDeInconsis" +
            "tenciasFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeAvisoPrevio/CalculeDataDePrevisaoDaRescisaoInconsistenciaF" +
            "ault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeAvisoPrevio/CalculeDataDePrevisaoDaRescisaoFalhaInternaDeE" +
            "xecucaoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeAvisoPrevio/CalculeDataDePrevisaoDaRescisaoFalhaDePermissa" +
            "oFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.CalculeDataDePrevisaoDaRescisaoResponse CalculeDataDePrevisaoDaRescisao(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.CalculeDataDePrevisaoDaRescisaoRequest request);
        
        // CODEGEN: Generating message contract since message ValideRegrasImpeditivasParaCadastroRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeAvisoPrevio/ValideRegrasImpeditivasParaCadastro", ReplyAction="lg.com.br/svc/ServicoDeAvisoPrevio/ValideRegrasImpeditivasParaCadastroResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeAvisoPrevio/ValideRegrasImpeditivasParaCadastroListaDeInco" +
            "nsistenciasFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeAvisoPrevio/ValideRegrasImpeditivasParaCadastroInconsisten" +
            "ciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeAvisoPrevio/ValideRegrasImpeditivasParaCadastroFalhaIntern" +
            "aDeExecucaoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeAvisoPrevio/ValideRegrasImpeditivasParaCadastroFalhaDePerm" +
            "issaoFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ValideRegrasImpeditivasParaCadastroResponse ValideRegrasImpeditivasParaCadastro(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ValideRegrasImpeditivasParaCadastroRequest request);
        
        // CODEGEN: Generating message contract since message ConsulteListaDeTiposRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeAvisoPrevio/ConsulteListaDeTipos", ReplyAction="lg.com.br/svc/ServicoDeAvisoPrevio/ConsulteListaDeTiposResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeAvisoPrevio/ConsulteListaDeTiposInconsistenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeAvisoPrevio/ConsulteListaDeTiposListaDeInconsistenciasFaul" +
            "t", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeAvisoPrevio/ConsulteListaDeTiposFalhaInternaDeExecucaoFaul" +
            "t", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeAvisoPrevio/ConsulteListaDeTiposFalhaDePermissaoFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ConsulteListaDeTiposResponse ConsulteListaDeTipos(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ConsulteListaDeTiposRequest request);
        
        // CODEGEN: Generating message contract since message ValideRegrasNaoImpeditivasParaCadastroRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeAvisoPrevio/ValideRegrasNaoImpeditivasParaCadastro", ReplyAction="lg.com.br/svc/ServicoDeAvisoPrevio/ValideRegrasNaoImpeditivasParaCadastroResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeAvisoPrevio/ValideRegrasNaoImpeditivasParaCadastroListaDeI" +
            "nconsistenciasFault", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeAvisoPrevio/ValideRegrasNaoImpeditivasParaCadastroInconsis" +
            "tenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeAvisoPrevio/ValideRegrasNaoImpeditivasParaCadastroFalhaInt" +
            "ernaDeExecucaoFault", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeAvisoPrevio/ValideRegrasNaoImpeditivasParaCadastroFalhaDeP" +
            "ermissaoFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ValideRegrasNaoImpeditivasParaCadastroResponse ValideRegrasNaoImpeditivasParaCadastro(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ValideRegrasNaoImpeditivasParaCadastroRequest request);
        
        // CODEGEN: Generating message contract since message ConsulteOcorrenciasRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="lg.com.br/svc/ServicoDeAvisoPrevio/ConsulteOcorrencias", ReplyAction="lg.com.br/svc/ServicoDeAvisoPrevio/ConsulteOcorrenciasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.Inconsistencia), Action="lg.com.br/svc/ServicoDeAvisoPrevio/ConsulteOcorrenciasInconsistenciaFault", Name="Inconsistencia", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ListaDeInconsistencias), Action="lg.com.br/svc/ServicoDeAvisoPrevio/ConsulteOcorrenciasListaDeInconsistenciasFault" +
            "", Name="ListaDeInconsistencias", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.FalhaInternaDeExecucao), Action="lg.com.br/svc/ServicoDeAvisoPrevio/ConsulteOcorrenciasFalhaInternaDeExecucaoFault" +
            "", Name="FalhaInternaDeExecucao", Namespace="lg.com.br/svc/dto")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.FalhaDePermissao), Action="lg.com.br/svc/ServicoDeAvisoPrevio/ConsulteOcorrenciasFalhaDePermissaoFault", Name="FalhaDePermissao", Namespace="lg.com.br/svc/dto")]
        WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ConsulteOcorrenciasResponse ConsulteOcorrencias(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ConsulteOcorrenciasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Cadastre", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class CadastreRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.AvisoPrevio AvisoPrevio;
        
        public CadastreRequest() {
        }
        
        public CadastreRequest(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.AvisoPrevio AvisoPrevio) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.AvisoPrevio = AvisoPrevio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CadastreResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class CadastreResponse {
        
        public CadastreResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculeDataDePrevisaoDaRescisao", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class CalculeDataDePrevisaoDaRescisaoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public int CodigoEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=1)]
        public int MatriculaFuncionario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=2)]
        public System.Nullable<System.DateTime> DataAvisoPrevio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=3)]
        public int TipoAvisoPrevio;
        
        public CalculeDataDePrevisaoDaRescisaoRequest() {
        }
        
        public CalculeDataDePrevisaoDaRescisaoRequest(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresa, int MatriculaFuncionario, System.Nullable<System.DateTime> DataAvisoPrevio, int TipoAvisoPrevio) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.CodigoEmpresa = CodigoEmpresa;
            this.MatriculaFuncionario = MatriculaFuncionario;
            this.DataAvisoPrevio = DataAvisoPrevio;
            this.TipoAvisoPrevio = TipoAvisoPrevio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculeDataDePrevisaoDaRescisaoResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class CalculeDataDePrevisaoDaRescisaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public System.DateTime CalculeDataDePrevisaoDaRescisaoResult;
        
        public CalculeDataDePrevisaoDaRescisaoResponse() {
        }
        
        public CalculeDataDePrevisaoDaRescisaoResponse(System.DateTime CalculeDataDePrevisaoDaRescisaoResult) {
            this.CalculeDataDePrevisaoDaRescisaoResult = CalculeDataDePrevisaoDaRescisaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValideRegrasImpeditivasParaCadastro", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ValideRegrasImpeditivasParaCadastroRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.AvisoPrevio AvisoPrevio;
        
        public ValideRegrasImpeditivasParaCadastroRequest() {
        }
        
        public ValideRegrasImpeditivasParaCadastroRequest(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.AvisoPrevio AvisoPrevio) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.AvisoPrevio = AvisoPrevio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValideRegrasImpeditivasParaCadastroResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ValideRegrasImpeditivasParaCadastroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.InconsistenciaComCampo[] ValideRegrasImpeditivasParaCadastroResult;
        
        public ValideRegrasImpeditivasParaCadastroResponse() {
        }
        
        public ValideRegrasImpeditivasParaCadastroResponse(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.InconsistenciaComCampo[] ValideRegrasImpeditivasParaCadastroResult) {
            this.ValideRegrasImpeditivasParaCadastroResult = ValideRegrasImpeditivasParaCadastroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsulteListaDeTipos", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ConsulteListaDeTiposRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public short Empresa;
        
        public ConsulteListaDeTiposRequest() {
        }
        
        public ConsulteListaDeTiposRequest(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao, short Empresa) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.Empresa = Empresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsulteListaDeTiposResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ConsulteListaDeTiposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.TipoAvisoPrevio[] ConsulteListaDeTiposResult;
        
        public ConsulteListaDeTiposResponse() {
        }
        
        public ConsulteListaDeTiposResponse(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.TipoAvisoPrevio[] ConsulteListaDeTiposResult) {
            this.ConsulteListaDeTiposResult = ConsulteListaDeTiposResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValideRegrasNaoImpeditivasParaCadastro", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ValideRegrasNaoImpeditivasParaCadastroRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.AvisoPrevio AvisoPrevio;
        
        public ValideRegrasNaoImpeditivasParaCadastroRequest() {
        }
        
        public ValideRegrasNaoImpeditivasParaCadastroRequest(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.AvisoPrevio AvisoPrevio) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.AvisoPrevio = AvisoPrevio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValideRegrasNaoImpeditivasParaCadastroResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ValideRegrasNaoImpeditivasParaCadastroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.InconsistenciaComCampo[] ValideRegrasNaoImpeditivasParaCadastroResult;
        
        public ValideRegrasNaoImpeditivasParaCadastroResponse() {
        }
        
        public ValideRegrasNaoImpeditivasParaCadastroResponse(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.InconsistenciaComCampo[] ValideRegrasNaoImpeditivasParaCadastroResult) {
            this.ValideRegrasNaoImpeditivasParaCadastroResult = ValideRegrasNaoImpeditivasParaCadastroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsulteOcorrencias", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ConsulteOcorrenciasRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="lg.com.br/svc/dto")]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public int CodigoEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=1)]
        public int MatriculaFuncionario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=2)]
        public bool IndicadorDeAvisoPrevioAtivo;
        
        public ConsulteOcorrenciasRequest() {
        }
        
        public ConsulteOcorrenciasRequest(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresa, int MatriculaFuncionario, bool IndicadorDeAvisoPrevioAtivo) {
            this.LGContextoAmbiente = LGContextoAmbiente;
            this.LGAutenticacao = LGAutenticacao;
            this.CodigoEmpresa = CodigoEmpresa;
            this.MatriculaFuncionario = MatriculaFuncionario;
            this.IndicadorDeAvisoPrevioAtivo = IndicadorDeAvisoPrevioAtivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsulteOcorrenciasResponse", WrapperNamespace="lg.com.br/svc", IsWrapped=true)]
    public partial class ConsulteOcorrenciasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="lg.com.br/svc", Order=0)]
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.AvisoPrevioConsulta[] ConsulteOcorrenciasResult;
        
        public ConsulteOcorrenciasResponse() {
        }
        
        public ConsulteOcorrenciasResponse(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.AvisoPrevioConsulta[] ConsulteOcorrenciasResult) {
            this.ConsulteOcorrenciasResult = ConsulteOcorrenciasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoDeAvisoPrevioChannel : WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ServicoDeAvisoPrevio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoDeAvisoPrevioClient : System.ServiceModel.ClientBase<WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ServicoDeAvisoPrevio>, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ServicoDeAvisoPrevio {
        
        public ServicoDeAvisoPrevioClient() {
        }
        
        public ServicoDeAvisoPrevioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoDeAvisoPrevioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoDeAvisoPrevioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoDeAvisoPrevioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.CadastreResponse WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ServicoDeAvisoPrevio.Cadastre(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.CadastreRequest request) {
            return base.Channel.Cadastre(request);
        }
        
        public void Cadastre(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.AvisoPrevio AvisoPrevio) {
            WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.CadastreRequest inValue = new WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.CadastreRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.AvisoPrevio = AvisoPrevio;
            WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.CadastreResponse retVal = ((WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ServicoDeAvisoPrevio)(this)).Cadastre(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.CalculeDataDePrevisaoDaRescisaoResponse WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ServicoDeAvisoPrevio.CalculeDataDePrevisaoDaRescisao(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.CalculeDataDePrevisaoDaRescisaoRequest request) {
            return base.Channel.CalculeDataDePrevisaoDaRescisao(request);
        }
        
        public System.DateTime CalculeDataDePrevisaoDaRescisao(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresa, int MatriculaFuncionario, System.Nullable<System.DateTime> DataAvisoPrevio, int TipoAvisoPrevio) {
            WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.CalculeDataDePrevisaoDaRescisaoRequest inValue = new WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.CalculeDataDePrevisaoDaRescisaoRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.CodigoEmpresa = CodigoEmpresa;
            inValue.MatriculaFuncionario = MatriculaFuncionario;
            inValue.DataAvisoPrevio = DataAvisoPrevio;
            inValue.TipoAvisoPrevio = TipoAvisoPrevio;
            WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.CalculeDataDePrevisaoDaRescisaoResponse retVal = ((WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ServicoDeAvisoPrevio)(this)).CalculeDataDePrevisaoDaRescisao(inValue);
            return retVal.CalculeDataDePrevisaoDaRescisaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ValideRegrasImpeditivasParaCadastroResponse WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ServicoDeAvisoPrevio.ValideRegrasImpeditivasParaCadastro(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ValideRegrasImpeditivasParaCadastroRequest request) {
            return base.Channel.ValideRegrasImpeditivasParaCadastro(request);
        }
        
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.InconsistenciaComCampo[] ValideRegrasImpeditivasParaCadastro(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.AvisoPrevio AvisoPrevio) {
            WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ValideRegrasImpeditivasParaCadastroRequest inValue = new WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ValideRegrasImpeditivasParaCadastroRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.AvisoPrevio = AvisoPrevio;
            WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ValideRegrasImpeditivasParaCadastroResponse retVal = ((WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ServicoDeAvisoPrevio)(this)).ValideRegrasImpeditivasParaCadastro(inValue);
            return retVal.ValideRegrasImpeditivasParaCadastroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ConsulteListaDeTiposResponse WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ServicoDeAvisoPrevio.ConsulteListaDeTipos(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ConsulteListaDeTiposRequest request) {
            return base.Channel.ConsulteListaDeTipos(request);
        }
        
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.TipoAvisoPrevio[] ConsulteListaDeTipos(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao, short Empresa) {
            WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ConsulteListaDeTiposRequest inValue = new WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ConsulteListaDeTiposRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.Empresa = Empresa;
            WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ConsulteListaDeTiposResponse retVal = ((WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ServicoDeAvisoPrevio)(this)).ConsulteListaDeTipos(inValue);
            return retVal.ConsulteListaDeTiposResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ValideRegrasNaoImpeditivasParaCadastroResponse WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ServicoDeAvisoPrevio.ValideRegrasNaoImpeditivasParaCadastro(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ValideRegrasNaoImpeditivasParaCadastroRequest request) {
            return base.Channel.ValideRegrasNaoImpeditivasParaCadastro(request);
        }
        
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.InconsistenciaComCampo[] ValideRegrasNaoImpeditivasParaCadastro(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.AvisoPrevio AvisoPrevio) {
            WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ValideRegrasNaoImpeditivasParaCadastroRequest inValue = new WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ValideRegrasNaoImpeditivasParaCadastroRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.AvisoPrevio = AvisoPrevio;
            WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ValideRegrasNaoImpeditivasParaCadastroResponse retVal = ((WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ServicoDeAvisoPrevio)(this)).ValideRegrasNaoImpeditivasParaCadastro(inValue);
            return retVal.ValideRegrasNaoImpeditivasParaCadastroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ConsulteOcorrenciasResponse WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ServicoDeAvisoPrevio.ConsulteOcorrencias(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ConsulteOcorrenciasRequest request) {
            return base.Channel.ConsulteOcorrencias(request);
        }
        
        public WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.AvisoPrevioConsulta[] ConsulteOcorrencias(WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGContextoAmbiente LGContextoAmbiente, WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.LGAutenticacao LGAutenticacao, int CodigoEmpresa, int MatriculaFuncionario, bool IndicadorDeAvisoPrevioAtivo) {
            WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ConsulteOcorrenciasRequest inValue = new WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ConsulteOcorrenciasRequest();
            inValue.LGContextoAmbiente = LGContextoAmbiente;
            inValue.LGAutenticacao = LGAutenticacao;
            inValue.CodigoEmpresa = CodigoEmpresa;
            inValue.MatriculaFuncionario = MatriculaFuncionario;
            inValue.IndicadorDeAvisoPrevioAtivo = IndicadorDeAvisoPrevioAtivo;
            WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ConsulteOcorrenciasResponse retVal = ((WCFTestClient.Dominio.ServicoDeAvisoPrevio_20171.ServicoDeAvisoPrevio)(this)).ConsulteOcorrencias(inValue);
            return retVal.ConsulteOcorrenciasResult;
        }
    }
}
